import {createSaveQueue} from './save-queue.mjs';
export const BOARD_CACHE_LIMITS={boards:10,bytes:32*1024*1024,ttlMs:5*60*1000,dirtyBoards:8};
// Each board owns its acknowledgement stream. Switching views never redirects
// an old reply into the active canvas. Dirty sessions are retained until saved.
export function createBoardCache({apply,send,onBoard,onState=()=>{},onError=()=>{},canPublish=()=>true,now=()=>Date.now(),limits=BOARD_CACHE_LIMITS,queueOptions={}}){
 const entries=new Map();let active=null;
 const bytes=b=>new TextEncoder().encode(JSON.stringify(b)).length;
 function state(){const busy=[...entries.values()].map(e=>e.queue.state).filter(s=>s.phase==='error'||s.phase==='saving'||s.phase==='scheduled');if(!busy.length)return entries.get(active)?.queue.state||{phase:'idle',pending:0,saved:0,total:0};const errors=busy.filter(s=>s.phase==='error');return {phase:errors.length?'error':busy.some(s=>s.phase==='saving')?'saving':'scheduled',pending:busy.reduce((n,s)=>n+s.pending,0),saved:busy.reduce((n,s)=>n+s.saved,0),total:busy.reduce((n,s)=>n+s.total,0),boards:busy.length,error:errors[0]?.error};}
 function emit(){onState(state());}
 function trim(){const clean=[...entries.values()].filter(e=>e.id!==active&&!e.queue.pending).sort((a,b)=>a.used-b.used);let total=[...entries.values()].reduce((n,e)=>n+e.bytes,0);for(const e of clean)if(now()-e.used>limits.ttlMs||entries.size>limits.boards||total>limits.bytes){entries.delete(e.id);e.queue.dispose();total-=e.bytes;}}
 // Accept emits saved state synchronously. Measure its final envelope once,
 // after any reentrant callbacks; ordinary acknowledgements still size freshly.
 function accept(board){if(!board)return;let entry=entries.get(board.id);if(!entry){entry={id:board.id,used:now(),bytes:0,accepting:0,ui:null,checked:now(),queue:null};entries.set(board.id,entry);entry.queue=createSaveQueue({...queueOptions,getBoard:()=>board,apply,send,canPublish:()=>active!==entry.id||canPublish(),onBoard:next=>{entry.used=now();if(active===entry.id)onBoard(next);},onState:s=>{if(entry.queue&&s.phase==='saved'&&!entry.accepting){entry.bytes=bytes(entry.queue.board);trim();}emit();},onError:e=>onError(e,entry.id)});}entry.accepting++;try{entry.queue.accept(board);}finally{entry.accepting--;}entry.bytes=bytes(entry.queue.board);entry.used=now();entry.checked=now();trim();return entry.queue.board;}
 function get(id){const entry=entries.get(id);if(!entry)return null;if(id!==active&&!entry.queue.pending&&now()-entry.used>limits.ttlMs){entry.queue.dispose();entries.delete(id);return null;}entry.used=now();return {board:entry.queue.board,ui:entry.ui,checked:entry.checked};}
 function activate(board){const dirty=[...entries.values()].filter(e=>e.queue.pending).length;if(active!==board.id&&dirty>=limits.dirtyBoards&&!entries.has(board.id))throw Error('Several boards still have unsaved edits. Retry saving before opening another board.');active=board.id;const entry=entries.get(board.id);let next;if(entry?.queue.board===board){entry.used=now();next=board;trim();}else next=accept(board);emit();return next;}
 function queue(){const q=entries.get(active)?.queue;if(!q)throw Error('Choose a board first.');return q;}
 return {accept,activate,get,deactivate(){active=null;emit();},capture(ui){const e=entries.get(active);if(e)e.ui=ui;},markChecked(id){const e=entries.get(id);if(e)e.checked=now();},invalidate(id){const e=entries.get(id);if(e&&!e.queue.pending){e.queue.dispose();entries.delete(id);}},enqueue:a=>{if(!queue().pending&&[...entries.values()].filter(e=>e.queue.pending).length>=limits.dirtyBoards)throw Error('Several boards still have unsaved edits. Retry saving before editing another board.');return queue().enqueue(a);},history:d=>queue().history(d),flush:async()=>entries.get(active)?.queue.flush(),flushAll:async()=>{for(const e of entries.values())await e.queue.flush();},retry:async()=>{for(const e of entries.values())if(e.queue.state.phase==='error')await e.queue.retry();},publish:()=>entries.get(active)?.queue.publish(),get board(){return entries.get(active)?.queue.board||null;},get pending(){return entries.get(active)?.queue.pending||false;},get anyPending(){return [...entries.values()].some(e=>e.queue.pending);},get draft(){return {boards:[...entries.values()].filter(e=>e.queue.pending).map(e=>e.queue.draft)};},get state(){return state();},dispose(){for(const e of entries.values())e.queue.dispose();entries.clear();}};
}
