import React,{useLayoutEffect,useRef,useState} from 'react';
import {BOARD_SECTION_LIMITS,boardSectionMaximum,clampBoardHeight,readBoardHeight,saveBoardHeight} from './board-section.mjs';
export function BoardSection({children}){
 const section=useRef(null),drag=useRef(null),maxRef=useRef(BOARD_SECTION_LIMITS.default),[preferred,setPreferred]=useState(readBoardHeight),[maximum,setMaximum]=useState(BOARD_SECTION_LIMITS.default),height=clampBoardHeight(preferred,maximum);
 useLayoutEffect(()=>{const panel=section.current.closest('.layers-panel'),measure=()=>{const max=boardSectionMaximum(panel.clientHeight,panel.querySelector('.panel-tabs')?.offsetHeight||0,panel.querySelector('.left-footer')?.offsetHeight||0);maxRef.current=max;setMaximum(max);};measure();const observer=new ResizeObserver(measure);observer.observe(panel);return()=>{observer.disconnect();if(drag.current){document.body.classList.remove('resizing-board-section');drag.current=null;}};},[]);
 function commit(value){const next=clampBoardHeight(value,maxRef.current);section.current.style.height=next+'px';setPreferred(next);saveBoardHeight(next);}
 function finish(event,cancel=false){const d=drag.current;if(!d)return;drag.current=null;document.body.classList.remove('resizing-board-section');if(cancel)section.current.style.height=clampBoardHeight(d.preferred,maxRef.current)+'px';else commit(d.next);if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);}
 return <><div ref={section} className="board-section is-resizable" style={{height}}>{children}</div><div className="board-section-resizer" role="separator" tabIndex={0} aria-label="Resize boards section height" aria-orientation="horizontal" aria-valuemin={BOARD_SECTION_LIMITS.min} aria-valuemax={maximum} aria-valuenow={height} aria-valuetext={height+' pixels'} title="Drag to resize boards · Arrow keys adjust · Double-click resets" onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.currentTarget.focus();drag.current={y:e.clientY,start:height,next:height,preferred};document.body.classList.add('resizing-board-section');e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d)return;d.next=clampBoardHeight(d.start+e.clientY-d.y,maxRef.current);section.current.style.height=d.next+'px';}} onPointerUp={e=>finish(e)} onPointerCancel={e=>finish(e,true)} onLostPointerCapture={e=>finish(e,true)} onDoubleClick={()=>commit(BOARD_SECTION_LIMITS.default)} onKeyDown={e=>{if(!['ArrowUp','ArrowDown','Home','End','Escape'].includes(e.key))return;e.preventDefault();if(e.key==='Escape')return finish(e,true);if(drag.current)return;commit(e.key==='Home'?BOARD_SECTION_LIMITS.min:e.key==='End'?maximum:height+(e.key==='ArrowDown'?1:-1)*(e.shiftKey?40:10));}}/></>;
}
