import React,{useState,useRef,useLayoutEffect,useEffect,useMemo,useId} from 'react';
import {Icon} from './icons.jsx';
import {newId} from '../shared/design.mjs';
import {belongsToFrame,overlayPath} from '../shared/flow-overlay.mjs';
import './flow-overlay.css';
import {FramePicker} from './FlowsEditor.jsx';
import {FlowReferenceFrame} from './FlowReferenceFrame.jsx';
function fallbackBounds(map,id){const n=map.get(id);if(!n)return null;let left=n.x,top=n.y,p=map.get(n.parentId),depth=0;while(p&&depth++<101){left+=p.x;top+=p.y;p=map.get(p.parentId);}return {left,top,width:n.width,height:n.height};}
export function FlowOverlay({board,document,viewport,canvasRef,canvasSize,onOperations,onHighlight,busy,api,workspaces,onFit}){
 const edges=document.flowOverlay?.edges||[],references=document.flowOverlay?.frames||[],frames=useMemo(()=>[...document.nodes.filter(n=>n.type==='frame'),...references.map(f=>({...f,name:f.reference.name||'Linked frame'}))],[document.nodes,document.flowOverlay]);
 const [picker,setPicker]=useState(false),[loaded,setLoaded]=useState({}),[positions,setPositions]=useState({}),[sourceElements,setSourceElements]=useState([]),[sourceLoading,setSourceLoading]=useState(false);
 const [hover,setHover]=useState(null),[editor,setEditor]=useState(null),[paths,setPaths]=useState([]),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const popoverRef=useRef(null),leave=useRef(null),pinned=useRef(false),marker=useId().replaceAll(':','');
 const active=edges.find(e=>e.id===hover),nodes=document.nodes,map=useMemo(()=>new Map(nodes.map(n=>[n.id,n])),[nodes]);
 function clear(){clearTimeout(leave.current);pinned.current=false;setHover(null);}
 function enter(id){clearTimeout(leave.current);setHover(id);}
 function exit(){if(!pinned.current)leave.current=setTimeout(()=>setHover(null),150);}
 useEffect(()=>{onHighlight(active&&!references.some(f=>f.id===active.fromFrameId)?active.triggerId||active.fromFrameId:null);return()=>onHighlight(null);},[active?.id,active?.triggerId,active?.fromFrameId]);
 useEffect(()=>{let alive=true;const source=references.find(f=>f.id===editor?.fromFrameId);setSourceElements([]);setSourceLoading(!!source);if(source)api(`/api/boards/${source.reference.boardId}/flow-sources?frameId=${source.reference.frameId}`).then(d=>{if(alive)setSourceElements(d.elements);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setSourceLoading(false);});return()=>{alive=false;};},[editor?.fromFrameId]);
 useEffect(()=>()=>clearTimeout(leave.current),[]);
 useEffect(()=>{if(hover&&!active)clear();},[active,hover]);
 useEffect(()=>{const close=e=>{if(e.key==='Escape'){clear();setEditor(null);}else if(e.type==='pointerdown'&&!e.target.closest('.flow-overlay,.flow-overlay-dialog'))clear();};window.addEventListener('keydown',close);window.addEventListener('pointerdown',close);return()=>{window.removeEventListener('keydown',close);window.removeEventListener('pointerdown',close);};},[]);
 useLayoutEffect(()=>{
  const canvas=canvasRef.current;if(!canvas)return;const rect=canvas.getBoundingClientRect(),elements=new Map([...canvas.querySelectorAll('[data-node-id]')].map(el=>[el.dataset.nodeId,el]));
  const bounds=id=>{const reference=references.find(f=>f.id===id);if(reference){const native=canvas.querySelector(`[data-flow-frame="${id}"] > [data-flow-element]`);if(native){const r=native.getBoundingClientRect();return {left:(r.left-rect.left-viewport.x)/viewport.zoom,top:(r.top-rect.top-viewport.y)/viewport.zoom,width:r.width/viewport.zoom,height:r.height/viewport.zoom};}const position=positions[id]||reference,root=loaded[id]?.nodes[0];return {left:position.x,top:position.y,width:root?.width||reference.width,height:root?.height||reference.height};}const el=elements.get(id);if(!el||!el.getClientRects().length)return fallbackBounds(map,id);const r=el.getBoundingClientRect();return {left:(r.left-rect.left-viewport.x)/viewport.zoom,top:(r.top-rect.top-viewport.y)/viewport.zoom,width:r.width/viewport.zoom,height:r.height/viewport.zoom};};
  const lanes=new Map();setPaths(edges.map(edge=>{const from=bounds(edge.fromFrameId),to=bounds(edge.toFrameId);if(!from||!to)return null;const pair=[edge.fromFrameId,edge.toFrameId].sort().join('_'),lane=lanes.get(pair)||0;lanes.set(pair,lane+1);const geometry=overlayPath(from,to,{loop:edge.fromFrameId===edge.toFrameId,repeat:edge.action==='repeat',lane}),convert=p=>({x:p.x*viewport.zoom+viewport.x,y:p.y*viewport.zoom+viewport.y}),[a,b,c,d]=geometry.points.map(convert);return {edge,d:`M ${a.x} ${a.y} C ${b.x} ${b.y} ${c.x} ${c.y} ${d.x} ${d.y}`,label:convert(geometry.label)};}).filter(Boolean));
 },[document,viewport,canvasSize,hover,positions,loaded]);
 function edit(edge){clear();setError('');setEditor(edge?structuredClone(edge):{id:newId('transition'),fromFrameId:frames[0]?.id||'',toFrameId:frames[1]?.id||frames[0]?.id||'',triggerId:null,action:frames.length===1?'repeat':'straight',title:'Continue',explanation:''});}
 async function save(operation,label){setSaving(true);setError('');try{await onOperations([operation],label);setEditor(null);clear();}catch(e){setError(e.message);}finally{setSaving(false);}}
 async function addReference(reference){setSaving(true);setError('');try{const source=await api(`/api/boards/${reference.boardId}/flow-sources?frameId=${reference.frameId}`),right=Math.max(0,...document.nodes.filter(n=>!n.parentId).map(n=>n.x+n.width),...references.map(f=>f.x+f.width));await onOperations([{op:'addFrame',frame:{id:newId('flow_frame'),reference,x:right+180,y:100,width:source.frame.width,height:source.frame.height}}],'Add frame reference');setPicker(false);requestAnimationFrame(onFit);}catch(e){setError(e.message);}finally{setSaving(false);}}
 const nameOf=id=>loaded[id]?.nodes[0]?.name||frames.find(f=>f.id===id)?.name||id;
 function frameLabel(frame){if(frame.reference)return '↗ '+(loaded[frame.id]?.nodes[0]?.name||frame.name);let path=[frame.name],p=map.get(frame.parentId),depth=0;while(p&&depth++<101){path.unshift(p.name);p=map.get(p.parentId);}return path.join(' / ');}
 const externalSource=references.find(f=>f.id===editor?.fromFrameId),triggerNodes=externalSource?sourceElements:nodes.filter(n=>n.id!==editor?.fromFrameId&&belongsToFrame(map,n.id,editor?.fromFrameId));
 const hoverPath=paths.find(p=>p.edge.id===hover),size={width:canvasRef.current?.clientWidth||600,height:canvasRef.current?.clientHeight||500};
 return <>
  <div className="flow-overlay" onPointerDown={e=>e.stopPropagation()} onDoubleClick={e=>e.stopPropagation()}>
   <div className="flow-layer-toolbar"><Icon name="link" size={15}/><strong>Flow layer</strong><button disabled={busy||saving} onClick={()=>{clear();setPicker(true);}}><Icon name="frame" size={14}/>Frame reference</button><span>{edges.length} {edges.length===1?'transition':'transitions'}</span><button disabled={!frames.length||busy||saving} onClick={()=>edit()}><Icon name="plus" size={14}/>Transition</button>{!frames.length&&<small>Add a design frame first.</small>}</div>
   <div className="flow-reference-world" style={{transform:`translate(${viewport.x}px,${viewport.y}px) scale(${viewport.zoom})`}}>{references.filter(f=>{const position=positions[f.id]||f,z=viewport.zoom;return active?.fromFrameId===f.id||position.x*z+viewport.x+f.width*z>=-160&&position.y*z+viewport.y+f.height*z>=-160&&position.x*z+viewport.x<=size.width+160&&position.y*z+viewport.y<=size.height+160;}).map(frame=><FlowReferenceFrame key={frame.id} {...{frame,viewport,api,busy}} highlight={active?.fromFrameId===frame.id?active.triggerId||frame.id:null} onLoaded={(id,doc)=>setLoaded(old=>({...old,[id]:doc?{nodes:doc.nodes.map((n,i)=>({id:n.id,name:n.name,...(!i?{width:n.width,height:n.height}:{})}))}:null}))} onPreviewMove={(id,position)=>setPositions(old=>{const next={...old};if(position)next[id]=position;else delete next[id];return next;})} onMove={(id,patch)=>onOperations([{op:'updateFrame',id,patch}],'Move frame reference')} onRemove={id=>save({op:'removeFrame',id},'Remove frame reference')}/>)}</div>
   <svg className="flow-overlay-arrows" aria-label="Frame transitions"><defs><marker id={marker} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#399cff"/></marker></defs>{paths.map(({edge,d})=><g key={edge.id} onMouseEnter={()=>enter(edge.id)} onMouseLeave={exit}><path className={'flow-arrow '+(hover===edge.id?'active':'')} d={d} markerEnd={'url(#'+marker+')'}/><path className="flow-arrow-hit" d={d}/></g>)}</svg>
   {paths.map(({edge,label})=><button key={edge.id} className={'flow-arrow-title '+(hover===edge.id?'active':'')} style={{left:label.x,top:label.y}} aria-label={'Transition: '+edge.title} onMouseEnter={()=>enter(edge.id)} onMouseLeave={exit} onFocus={()=>enter(edge.id)} onBlur={exit} onClick={()=>{pinned.current=true;enter(edge.id);}}>{edge.action!=='straight'&&<small>{edge.action==='if'?'If':'Repeat'}</small>}{edge.title}</button>)}
   {active&&hoverPath&&<section ref={popoverRef} className="flow-arrow-popover" role="dialog" aria-label="Transition details" onMouseEnter={()=>enter(active.id)} onMouseLeave={exit} style={{left:Math.max(8,Math.min(size.width-300,hoverPath.label.x-140)),top:Math.max(58,Math.min(size.height-(popoverRef.current?.offsetHeight||250)-8,hoverPath.label.y+22))}}><header><strong>{active.title}</strong><button aria-label="Close transition details" onClick={clear}><Icon name="close" size={14}/></button></header><small>{nameOf(active.fromFrameId)} → {nameOf(active.toFrameId)} · {active.action}</small><p>{active.explanation||'Add a description to explain this transition.'}</p><div className="flow-trigger-name"><span/>Trigger: {map.get(active.triggerId)?.name||loaded[active.fromFrameId]?.nodes.find(n=>n.id===active.triggerId)?.name||nameOf(active.fromFrameId)}</div><footer><button disabled={busy||saving} onClick={()=>edit(active)}><Icon name="edit" size={14}/>Edit</button><button className="danger-action" disabled={busy||saving} onClick={()=>save({op:'removeEdge',id:active.id},'Remove transition')}><Icon name="trash" size={14}/>Remove</button></footer>{error&&<p role="alert">{error}</p>}</section>}
   {!edges.length&&<div className="flow-overlay-empty">Connect existing frames with arrows. Hover an arrow to reveal its trigger and description.</div>}
  </div>
  {picker&&<div className="flow-overlay-dialog" onPointerDown={e=>e.stopPropagation()}><FramePicker api={api} workspaces={workspaces} busy={busy||saving} onChoose={addReference} onClose={()=>setPicker(false)}/>{error&&<p role="alert" className="flow-picker-error">{error}</p>}</div>}
  {editor&&<div className="dialog-backdrop flow-overlay-dialog" onPointerDown={e=>e.stopPropagation()} onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setEditor(null);}}><form className="studio-dialog" role="dialog" aria-label="Transition editor" onSubmit={e=>{e.preventDefault();save(edges.some(edge=>edge.id===editor.id)?{op:'updateEdge',id:editor.id,patch:Object.fromEntries(Object.entries(editor).filter(([k])=>k!=='id'))}:{op:'addEdge',edge:editor},edges.some(edge=>edge.id===editor.id)?'Edit transition':'Add transition');}}><div className="dialog-title"><h2>{edges.some(e=>e.id===editor.id)?'Edit transition':'Add transition'}</h2><button type="button" aria-label="Close transition editor" disabled={saving} onClick={()=>setEditor(null)}><Icon name="close"/></button></div><p>Connect native frames and references from other boards. Hover the arrow to reveal its exact trigger.</p><label>From frame<select aria-label="From frame" value={editor.fromFrameId} disabled={saving} onChange={e=>setEditor({...editor,fromFrameId:e.target.value,triggerId:null})}>{frames.map(f=><option key={f.id} value={f.id}>{frameLabel(f)}</option>)}</select></label><label>Trigger element<select aria-label="Trigger element" value={editor.triggerId||''} disabled={saving} onChange={e=>setEditor({...editor,triggerId:e.target.value||null})}><option value="">Frame state (no button)</option>{triggerNodes.filter(n=>n.id!==(externalSource?.reference.frameId||editor.fromFrameId)).map(n=><option key={n.id} value={n.id}>{n.name} · {n.type}</option>)}</select></label>{sourceLoading&&<small role="status">Loading source elements…</small>}<label>To frame<select aria-label="To frame" value={editor.toFrameId} disabled={saving} onChange={e=>setEditor({...editor,toFrameId:e.target.value})}>{frames.map(f=><option key={f.id} value={f.id}>{frameLabel(f)}</option>)}</select></label><label>Action<select aria-label="Transition action" value={editor.action} disabled={saving} onChange={e=>setEditor({...editor,action:e.target.value})}><option value="straight">Straight</option><option value="if">If / condition</option><option value="repeat">Repeat / loop</option></select></label><label>Title<input aria-label="Transition title" required maxLength={160} value={editor.title} disabled={saving} onChange={e=>setEditor({...editor,title:e.target.value})}/></label><label>Description<textarea aria-label="Transition description" maxLength={10000} rows={3} value={editor.explanation} disabled={saving} onChange={e=>setEditor({...editor,explanation:e.target.value})}/></label>{error&&<p role="alert" className="palette-error">{error}</p>}<div className="dialog-actions"><button type="button" disabled={saving} onClick={()=>setEditor(null)}>Cancel</button><button className="primary-button" type="submit" disabled={busy||saving||sourceLoading}>{saving?'Saving…':'Save transition'}</button></div></form></div>}
 </>;
}
