import React,{useState,useEffect,useMemo} from 'react';
import {layerStyle} from '../shared/design.mjs';
import {Icon} from './icons.jsx';
import {flowLink} from '../shared/flows.mjs';
import {workspaceTrail} from './editor.mjs';
import {subscribeBoardStatus} from './status-poll.mjs';
import './flows.css';
import './flow-overlay.css';
const elementLabel=n=>n?.type==='text'&&n.text?n.text.slice(0,100):n?.name;
function PreviewLayer({node,children,parent,highlight}){return <div className={highlight===node.id?'flow-trigger-highlight':''} style={layerStyle(node,parent,!parent)}>{node.type==='text'&&node.text}{node.type==='image'&&node.src&&<img src={node.src} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}} loading="lazy"/>}{node.type==='icon'&&<Icon name={node.icon} size="100%"/>}{node.type==='vector'&&<svg viewBox={node.viewBox.join(' ')} width="100%" height="100%">{node.paths.map((p,i)=><path key={i} {...p}/>)}</svg>}{(children.get(node.id)||[]).map(n=><PreviewLayer key={n.id} node={n} children={children} parent={node} highlight={highlight}/>)}</div>;}
export function FrameThumbnail({reference,api,highlight}){
 const [preview,setPreview]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let active=true,revision='',loading=false;setPreview(null);setError('');const missing=e=>{if(active){revision='';setError(e.message);setPreview(null);}};const load=async()=>{if(loading)return;loading=true;try{const d=await api(`/api/boards/${reference.boardId}/flow-preview?frameId=${reference.frameId}`);if(active){revision=[d.revision,d.paletteRevision,d.themeId].join(':');setPreview(d.document);setError('');}}catch(e){missing(e);}finally{loading=false;}};load();const stop=subscribeBoardStatus(api,reference.boardId,{interval:5000,canPoll:()=>!loading,onData:d=>{if(active&&[d.revision,d.paletteRevision,d.themeId].join(':')!==revision)return load();},onError:missing});return()=>{active=false;stop();};},[reference.boardId,reference.frameId]);
 const f=preview?.nodes[0],scale=f?Math.min(196/f.width,84/f.height):1,children=useMemo(()=>{const map=new Map();for(const n of preview?.nodes||[]){if(!map.has(n.parentId))map.set(n.parentId,[]);map.get(n.parentId).push(n);}return map;},[preview]);return <div className="flow-thumbnail" aria-label="Linked frame preview">{f?<div className="flow-thumbnail-world" style={{transform:`scale(${scale})`,width:f.width,height:f.height,left:(196-f.width*scale)/2,top:(84-f.height*scale)/2}}><PreviewLayer node={{...f,x:0,y:0}} children={children} highlight={highlight}/></div>:<small>{error?'Missing frame · select to relink':'Loading frame…'}</small>}</div>;}
export function EditField({label,value,onSave,multiline=false,disabled=false}){
 const [draft,setDraft]=useState(value||'');useEffect(()=>setDraft(value||''),[value]);const Tag=multiline?'textarea':'input';return <label className="flow-field">{label}<Tag aria-label={label} value={draft} maxLength={multiline?10000:200} disabled={disabled} onChange={e=>setDraft(e.target.value)} onBlur={()=>{if(draft!==value)onSave(draft);}} onKeyDown={e=>{if(!multiline&&e.key==='Enter')e.currentTarget.blur();}}/></label>;
}
export function FramePicker({api,workspaces,onChoose,onClose,busy}){
 const [workspace,setWorkspace]=useState(''),[boards,setBoards]=useState([]),[board,setBoard]=useState(''),[frames,setFrames]=useState([]),[frame,setFrame]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[query,setQuery]=useState(''),[nested,setNested]=useState(false);
 useEffect(()=>{let active=true;setBoards([]);setBoard('');setError('');if(workspace){setLoading(true);api(`/api/workspaces/${workspace}/boards`).then(d=>{if(active)setBoards(d.boards);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});}return()=>{active=false;};},[workspace]);
 useEffect(()=>{let active=true;setFrames([]);setFrame('');setQuery('');setNested(false);if(board){setLoading(true);api(`/api/boards/${board}/flow-sources`).then(d=>{if(active)setFrames(d.frames);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});}return()=>{active=false;};},[board]);
 const names=new Map(frames.map(f=>[f.id,f]));const label=f=>{const path=[f.name];let p=names.get(f.parentId),depth=0;while(p&&depth++<101){path.unshift(p.name);p=names.get(p.parentId);}return path.join(' / ');};
 return <div className="dialog-backdrop"><section className="studio-dialog flow-picker" role="dialog" aria-label="Pick existing frame"><div className="dialog-title"><h2>Add linked frame</h2><button aria-label="Close frame picker" onClick={onClose}>✕</button></div><p>Use a frame from any design workspace. Its original layers remain in place.</p><label>Workspace<select aria-label="Source workspace" value={workspace} onChange={e=>setWorkspace(e.target.value)}><option value="">Choose a workspace…</option>{workspaces.filter(w=>w.type!=='flows').map(w=><option key={w.id} value={w.id}>{workspaceTrail(workspaces,w.id).map(p=>p.name).join(' / ')}</option>)}</select></label><label>Board<select aria-label="Source board" value={board} onChange={e=>setBoard(e.target.value)} disabled={!workspace}><option value="">Choose a board…</option>{boards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Find a frame<input aria-label="Find source frame" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Frame name…"/></label><label className="flow-nested"><input type="checkbox" checked={nested} onChange={e=>setNested(e.target.checked)}/>Include nested frames</label><div className="flow-frame-options">{frames.filter(f=>(nested||!f.parentId)&&f.name.toLowerCase().includes(query.toLowerCase())).map(f=><button aria-pressed={frame===f.id} key={f.id} onClick={()=>setFrame(f.id)}>▣ <span><strong>{label(f)}</strong><small>{f.width} × {f.height}{f.parentId?' · nested frame':''}</small></span></button>)}{board&&!loading&&!frames.length&&<p>No frames on this board.</p>}</div>{loading&&<p role="status">Loading selected board…</p>}{error&&<p role="alert">{error}</p>}<footer className="dialog-actions"><button onClick={onClose}>Cancel</button><button className="primary-button" disabled={!frame||busy} onClick={()=>onChoose({workspaceId:workspace,boardId:board,frameId:frame,name:frames.find(f=>f.id===frame).name})}>Add frame</button></footer></section></div>;
}
export function ReferenceInfo({reference,api}){const [result,setResult]=useState(null);useEffect(()=>{let active=true;setResult(null);api('/api/flow-reference','POST',reference).then(d=>{if(active)setResult(d);}).catch(e=>{if(active)setResult({available:false,message:e.message});});return()=>{active=false;};},[reference.workspaceId,reference.boardId,reference.frameId]);return <div className="flow-reference"><small>ORIGINAL DESIGN</small><strong>{result?.frameName||reference.name||reference.frameId}</strong>{result?.available?<><p>{result.workspaceName} / {result.boardName}</p><a href={flowLink(reference)} target="_blank" rel="noreferrer">Open original frame ↗</a></>:<p role={result?'alert':undefined}>{result?.message||'Checking reference…'}</p>}</div>;}
export function TransitionFields({edge,nodes,api,onPatch,disabled}){
 const source=nodes.find(n=>n.id===edge.from),ref=source?.reference,[elements,setElements]=useState([]),[error,setError]=useState('');
 useEffect(()=>{let active=true;setElements([]);setError('');if(ref)api(`/api/boards/${ref.boardId}/flow-sources?frameId=${ref.frameId}`).then(d=>{if(active)setElements(d.elements);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[ref?.boardId,ref?.frameId]);
 return <><label className="flow-field">From<select aria-label="Transition from" value={edge.from} disabled={disabled} onChange={e=>onPatch({from:e.target.value})}>{nodes.filter(n=>n.kind!=='end').map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label className="flow-field">To<select aria-label="Transition to" value={edge.to} disabled={disabled} onChange={e=>onPatch({to:e.target.value})}>{nodes.filter(n=>n.kind!=='start').map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label className="flow-field">Action<select aria-label="Transition action" value={edge.action} disabled={disabled} onChange={e=>onPatch({action:e.target.value})}>{['straight','if','repeat'].map(a=><option key={a} value={a}>{a==='if'?'If / branch':a==='repeat'?'Repeat / loop':'Straight'}</option>)}</select></label><label className="flow-field">Trigger element<select aria-label="Trigger element" value={edge.trigger?.elementId||''} disabled={disabled||!ref} onChange={e=>onPatch({trigger:e.target.value?{...ref,elementId:e.target.value,name:elementLabel(elements.find(n=>n.id===e.target.value))}:null})}><option value="">No specific element</option>{edge.trigger&&!elements.some(n=>n.id===edge.trigger.elementId)&&<option value={edge.trigger.elementId}>Missing: {edge.trigger.name||edge.trigger.elementId}</option>}{elements.map(n=><option key={n.id} value={n.id}>{n.name} · {n.type}{n.text?' · '+n.text:''}</option>)}</select></label>{error&&<p role="alert">{error}</p>}<p>Pick the source button or layer. Add “Yes”, “No”, or a loop condition as the transition title.</p></>;
}
export {FlowsEditor} from './FlowWorkspace.jsx';
