import React,{useState,useEffect,useRef,useId,useMemo} from 'react';
import {newId,layerStyle} from '../shared/design.mjs';
import {Icon} from './icons.jsx';
import {flowLink} from '../shared/flows.mjs';
import {SidePanel} from './SidePanel.jsx';
import {workspaceTrail} from './editor.mjs';
import './flows.css';
const symbols={frame:'▣',if:'◇',repeat:'↻',end:'●'};
const elementLabel=n=>n?.type==='text'&&n.text?n.text.slice(0,100):n?.name;
function PreviewLayer({node,children,parent}){return <div style={layerStyle(node,parent,!parent)}>{node.type==='text'&&node.text}{node.type==='image'&&node.src&&<img src={node.src} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}} loading="lazy"/>}{node.type==='icon'&&<Icon name={node.icon} size="100%"/>}{node.type==='vector'&&<svg viewBox={node.viewBox.join(' ')} width="100%" height="100%">{node.paths.map((p,i)=><path key={i} {...p}/>)}</svg>}{(children.get(node.id)||[]).map(n=><PreviewLayer key={n.id} node={n} children={children} parent={node}/>)}</div>;}
function FrameThumbnail({reference,api}){const [preview,setPreview]=useState(null),[error,setError]=useState('');useEffect(()=>{let active=true,revision='';const load=()=>api(`/api/boards/${reference.boardId}/flow-preview?frameId=${reference.frameId}`).then(d=>{if(active){revision=[d.revision,d.paletteRevision,d.themeId].join(':');setPreview(d.document);setError('');}}).catch(e=>{if(active){setError(e.message);setPreview(null);}});load();const timer=setInterval(async()=>{if(document.hidden)return;try{const d=await api(`/api/boards/${reference.boardId}/status`);if(active&&[d.revision,d.paletteRevision,d.themeId].join(':')!==revision)load();}catch(e){if(active){setError(e.message);setPreview(null);}}},5000);return()=>{active=false;clearInterval(timer);};},[reference.boardId,reference.frameId]);const f=preview?.nodes[0],scale=f?Math.min(196/f.width,84/f.height):1,children=useMemo(()=>{const map=new Map();for(const n of preview?.nodes||[]){if(!map.has(n.parentId))map.set(n.parentId,[]);map.get(n.parentId).push(n);}return map;},[preview]);return <div className="flow-thumbnail" aria-label="Linked frame preview">{f?<div className="flow-thumbnail-world" style={{transform:`scale(${scale})`,width:f.width,height:f.height,left:(196-f.width*scale)/2,top:(84-f.height*scale)/2}}><PreviewLayer node={{...f,x:0,y:0}} children={children}/></div>:<small>{error?'Missing frame · select to relink':'Loading frame…'}</small>}</div>;}
function EditField({label,value,onSave,multiline=false,disabled=false}){
 const [draft,setDraft]=useState(value||'');useEffect(()=>setDraft(value||''),[value]);const Tag=multiline?'textarea':'input';return <label className="flow-field">{label}<Tag aria-label={label} value={draft} maxLength={multiline?10000:200} disabled={disabled} onChange={e=>setDraft(e.target.value)} onBlur={()=>{if(draft!==value)onSave(draft);}} onKeyDown={e=>{if(!multiline&&e.key==='Enter')e.currentTarget.blur();}}/></label>;
}
export function FramePicker({api,workspaces,onChoose,onClose,busy}){
 const [workspace,setWorkspace]=useState(''),[boards,setBoards]=useState([]),[board,setBoard]=useState(''),[frames,setFrames]=useState([]),[frame,setFrame]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[query,setQuery]=useState(''),[nested,setNested]=useState(false);
 useEffect(()=>{let active=true;setBoards([]);setBoard('');setError('');if(workspace){setLoading(true);api(`/api/workspaces/${workspace}/boards`).then(d=>{if(active)setBoards(d.boards);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});}return()=>{active=false;};},[workspace]);
 useEffect(()=>{let active=true;setFrames([]);setFrame('');setQuery('');setNested(false);if(board){setLoading(true);api(`/api/boards/${board}/flow-sources`).then(d=>{if(active)setFrames(d.frames);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});}return()=>{active=false;};},[board]);
 const names=new Map(frames.map(f=>[f.id,f]));const label=f=>{const path=[f.name];let p=names.get(f.parentId),depth=0;while(p&&depth++<101){path.unshift(p.name);p=names.get(p.parentId);}return path.join(' / ');};
 return <div className="dialog-backdrop"><section className="studio-dialog flow-picker" role="dialog" aria-label="Pick existing frame"><div className="dialog-title"><h2>Add linked frame</h2><button aria-label="Close frame picker" onClick={onClose}>✕</button></div><p>Use a frame from any design workspace. Its original layers remain in place.</p><label>Workspace<select aria-label="Source workspace" value={workspace} onChange={e=>setWorkspace(e.target.value)}><option value="">Choose a workspace…</option>{workspaces.filter(w=>w.type!=='flows').map(w=><option key={w.id} value={w.id}>{workspaceTrail(workspaces,w.id).map(p=>p.name).join(' / ')}</option>)}</select></label><label>Board<select aria-label="Source board" value={board} onChange={e=>setBoard(e.target.value)} disabled={!workspace}><option value="">Choose a board…</option>{boards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Find a frame<input aria-label="Find source frame" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Frame name…"/></label><label className="flow-nested"><input type="checkbox" checked={nested} onChange={e=>setNested(e.target.checked)}/>Include nested frames</label><div className="flow-frame-options">{frames.filter(f=>(nested||!f.parentId)&&f.name.toLowerCase().includes(query.toLowerCase())).map(f=><button aria-pressed={frame===f.id} key={f.id} onClick={()=>setFrame(f.id)}>▣ <span><strong>{label(f)}</strong><small>{f.width} × {f.height}{f.parentId?' · nested frame':''}</small></span></button>)}{board&&!loading&&!frames.length&&<p>No frames on this board.</p>}</div>{loading&&<p role="status">Loading selected board…</p>}{error&&<p role="alert">{error}</p>}<footer className="dialog-actions"><button onClick={onClose}>Cancel</button><button className="primary-button" disabled={!frame||busy} onClick={()=>onChoose({workspaceId:workspace,boardId:board,frameId:frame,name:frames.find(f=>f.id===frame).name})}>Add frame</button></footer></section></div>;
}
function ReferenceInfo({reference,api}){const [result,setResult]=useState(null);useEffect(()=>{let active=true;setResult(null);api('/api/flow-reference','POST',reference).then(d=>{if(active)setResult(d);}).catch(e=>{if(active)setResult({available:false,message:e.message});});return()=>{active=false;};},[reference.workspaceId,reference.boardId,reference.frameId]);return <div className="flow-reference"><small>ORIGINAL DESIGN</small><strong>{result?.frameName||reference.name||reference.frameId}</strong>{result?.available?<><p>{result.workspaceName} / {result.boardName}</p><a href={flowLink(reference)} target="_blank" rel="noreferrer">Open original frame ↗</a></>:<p role={result?'alert':undefined}>{result?.message||'Checking reference…'}</p>}</div>;}
function TransitionFields({edge,nodes,api,onPatch,disabled}){
 const source=nodes.find(n=>n.id===edge.from),ref=source?.reference,[elements,setElements]=useState([]),[error,setError]=useState('');
 useEffect(()=>{let active=true;setElements([]);setError('');if(ref)api(`/api/boards/${ref.boardId}/flow-sources?frameId=${ref.frameId}`).then(d=>{if(active)setElements(d.elements);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[ref?.boardId,ref?.frameId]);
 return <><label className="flow-field">From<select aria-label="Transition from" value={edge.from} disabled={disabled} onChange={e=>onPatch({from:e.target.value})}>{nodes.filter(n=>n.kind!=='end').map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label className="flow-field">To<select aria-label="Transition to" value={edge.to} disabled={disabled} onChange={e=>onPatch({to:e.target.value})}>{nodes.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label className="flow-field">Action<select aria-label="Transition action" value={edge.action} disabled={disabled} onChange={e=>onPatch({action:e.target.value})}>{['straight','if','repeat'].map(a=><option key={a} value={a}>{a==='if'?'If / branch':a==='repeat'?'Repeat / loop':'Straight'}</option>)}</select></label><label className="flow-field">Trigger element<select aria-label="Trigger element" value={edge.trigger?.elementId||''} disabled={disabled||!ref} onChange={e=>onPatch({trigger:e.target.value?{...ref,elementId:e.target.value,name:elementLabel(elements.find(n=>n.id===e.target.value))}:null})}><option value="">No specific element</option>{edge.trigger&&!elements.some(n=>n.id===edge.trigger.elementId)&&<option value={edge.trigger.elementId}>Missing: {edge.trigger.name||edge.trigger.elementId}</option>}{elements.map(n=><option key={n.id} value={n.id}>{n.name} · {n.type}{n.text?' · '+n.text:''}</option>)}</select></label>{error&&<p role="alert">{error}</p>}<p>Pick the source button or layer. Add “Yes”, “No”, or a loop condition as the transition title.</p></>;
}
function curve(a,b,loop){const x=a.x+240,y=a.y+(a.kind==='frame'?130:85),tx=b.x,ty=b.y+(b.kind==='frame'?130:85);if(loop||tx<x){const low=Math.max(y,ty)+130;return {path:`M ${x} ${y} C ${x+100} ${y} ${x+100} ${low} ${x} ${low} L ${tx-55} ${low} Q ${tx-90} ${low} ${tx-90} ${ty+35} Q ${tx-90} ${ty} ${tx-10} ${ty} L ${tx} ${ty}`,lx:(x+tx)/2,ly:low-14};}const dx=Math.max(65,(tx-x)/2);return {path:`M ${x} ${y} C ${x+dx} ${y} ${tx-dx} ${ty} ${tx} ${ty}`,lx:(x+tx)/2,ly:(y+ty)/2-18};}
export function FlowsEditor({board,boards,workspaces,api,busy,onOperations,onOpenBoard,onNewBoard,onDeleteBoard,onExport,onTask,panelProps,onUndo}){
 const [selected,setSelected]=useState(null),[picker,setPicker]=useState(false),[connecting,setConnecting]=useState(null),[view,setView]=useState({x:60,y:90,zoom:1}),[drag,setDrag]=useState(null),[error,setError]=useState('');const canvas=useRef(null),gesture=useRef(null),marker=useId().replaceAll(':','');const flow=board?.document.flow||{nodes:[],edges:[]},nodes=flow.nodes.map(n=>drag?.id===n.id?{...n,x:drag.x,y:drag.y}:n),node=nodes.find(n=>n.id===selected),edge=flow.edges.find(e=>e.id===selected),item=node||edge;
 useEffect(()=>{setSelected(null);setConnecting(null);setView({x:60,y:90,zoom:1});setPicker(false);setError('');},[board?.id]);
 useEffect(()=>{const el=canvas.current;if(!el)return;const prevent=e=>{if(e.ctrlKey||e.metaKey)e.preventDefault();};el.addEventListener('wheel',prevent,{passive:false});return()=>el.removeEventListener('wheel',prevent);},[]);
 async function action(ops,label){setError('');try{return await onOperations(ops,label);}catch(e){setError(e.message);}}
 function add(kind,reference){const n={id:newId('step'),kind,title:reference?.name||(kind==='if'?'Condition?':kind==='repeat'?'Repeat until…':'Complete'),explanation:'',x:Math.round((70-view.x)/view.zoom)+nodes.length%3*340,y:Math.round((90-view.y)/view.zoom)+Math.floor(nodes.length/3)*330,...(reference?{reference}:{})};action([{op:'addNode',node:n}],'Add '+kind+' step').then(result=>{if(result){setSelected(n.id);setPicker(false);}});}
 function connect(from,to){const s=nodes.find(n=>n.id===from);const e={id:newId('transition'),from,to,action:s.kind==='repeat'?'repeat':s.kind==='if'?'if':'straight',title:s.kind==='if'?'Yes':'',explanation:''};action([{op:'addEdge',edge:e}],'Connect steps').then(result=>{if(result)setSelected(e.id);});setConnecting(null);}
 function pick(n){if(connecting){connect(connecting,n.id);return;}setSelected(n.id);}
 function patch(values){if(item)action([{op:node?'updateNode':'updateEdge',id:item.id,patch:values}],'Edit '+(node?'step':'transition'));}
 function remove(){if(item)action([{op:node?'removeNode':'removeEdge',id:item.id}],'Delete '+(node?'step':'transition')).then(result=>{if(result)setSelected(null);});}
 useEffect(()=>{const handler=e=>{if(e.defaultPrevented||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;if(e.key==='Escape'){setConnecting(null);setPicker(false);setSelected(null);}if(['Delete','Backspace'].includes(e.key)&&item&&!busy){e.preventDefault();remove();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[item,busy,board?.revision]);
 function fit(){const el=canvas.current;if(!el||!nodes.length)return;const minX=Math.min(...nodes.map(n=>n.x))-150,minY=Math.min(...nodes.map(n=>n.y))-80,maxX=Math.max(...nodes.map(n=>n.x+240))+150,maxY=Math.max(...nodes.map(n=>n.y+300))+80,z=Math.min(1.5,el.clientWidth/(maxX-minX),el.clientHeight/(maxY-minY));setView({zoom:z,x:(el.clientWidth-(maxX-minX)*z)/2-minX*z,y:(el.clientHeight-(maxY-minY)*z)/2-minY*z});}
 function start(e,n){if(e.button!==0||busy||e.target.closest('button,a'))return;e.preventDefault();e.stopPropagation();if(connecting){pick(n);return;}setSelected(n.id);gesture.current={id:n.id,x:e.clientX,y:e.clientY,original:n};e.currentTarget.setPointerCapture(e.pointerId);}
 function move(e){const g=gesture.current;if(!g)return;if(g.id)setDrag({id:g.id,x:g.original.x+(e.clientX-g.x)/view.zoom,y:g.original.y+(e.clientY-g.y)/view.zoom});else setView({...g.view,x:g.view.x+e.clientX-g.x,y:g.view.y+e.clientY-g.y});}
 function finish(e,cancel=false){const g=gesture.current;if(!g)return;gesture.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(g.id&&drag&&!cancel&&(drag.x!==g.original.x||drag.y!==g.original.y))action([{op:'updateNode',id:g.id,patch:{x:Math.round(drag.x),y:Math.round(drag.y)}}],'Move flow step');setDrag(null);}
 return <><SidePanel {...panelProps('left')}><aside className="flow-sidebar"><div className="flow-section-heading">FLOW BOARDS <button aria-label="New flow board" onClick={onNewBoard}>＋</button></div>{boards.map(b=><div className="flow-board-row" key={b.id}><button className={b.id===board?.id?'active':''} onClick={()=>onOpenBoard(b.id)}>{b.name}</button><button aria-label={'Delete flow board '+b.name} onClick={()=>onDeleteBoard(b.id)}>⋯</button></div>)}<div className="flow-section-heading">STEPS <span>{nodes.length}</span></div>{nodes.map(n=><button className={'flow-list-step '+(selected===n.id?'active':'')} key={n.id} onClick={()=>{pick(n);setView(v=>({...v,x:70-n.x*v.zoom,y:100-n.y*v.zoom}));}}>{symbols[n.kind]} <span>{n.title}</span></button>)}<div className="flow-section-heading">TRANSITIONS <span>{flow.edges.length}</span></div>{flow.edges.map(e=><button className={'flow-list-step '+(selected===e.id?'active':'')} key={e.id} onClick={()=>setSelected(e.id)}>↗ <span>{e.title||e.action} <small>{nodes.find(n=>n.id===e.from)?.title} → {nodes.find(n=>n.id===e.to)?.title}</small></span></button>)}<p className="flow-help">Frame steps link to original designs. Change their layout and layers in the source workspace.</p></aside></SidePanel>
 <main className="flow-main"><nav className="flow-toolbar" aria-label="Flow tools"><button disabled={!board||busy} onClick={()=>setPicker('add')}>＋ Frame</button>{['if','repeat','end'].map(k=><button disabled={!board||busy} key={k} onClick={()=>add(k)}>{symbols[k]} {k==='end'?'End':k==='if'?'If':'Repeat'}</button>)}<button className={connecting?'active':''} disabled={!node||node.kind==='end'||busy} onClick={()=>setConnecting(connecting?null:node.id)}>↗ Connect</button><span/><button aria-label="Undo flow edit" disabled={!board?.canUndo||busy} onClick={()=>onUndo('undo')}>↶</button><button aria-label="Redo flow edit" disabled={!board?.canRedo||busy} onClick={()=>onUndo('redo')}>↷</button><button onClick={fit} disabled={!nodes.length}>Fit</button><select aria-label="Flow zoom" value={view.zoom} onChange={e=>setView({...view,zoom:Number(e.target.value)})}>{[...new Set([.25,.5,.75,1,1.25,1.5,2,view.zoom])].sort((a,b)=>a-b).map(z=><option key={z} value={z}>{Math.round(z*100)}%</option>)}</select></nav>
 <div className="flow-canvas" ref={canvas} aria-label="Flow canvas" onPointerDown={e=>{if(e.button!==0||e.target.closest('button,a,.flow-step,.flow-edge-label,.flow-edge'))return;setSelected(null);gesture.current={x:e.clientX,y:e.clientY,view};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={move} onPointerUp={finish} onPointerCancel={e=>finish(e,true)} onWheel={e=>{if(e.ctrlKey||e.metaKey){const rect=e.currentTarget.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,z=Math.max(.2,Math.min(2,view.zoom*Math.exp(-e.deltaY*.002)));setView({zoom:z,x:x-(x-view.x)*z/view.zoom,y:y-(y-view.y)*z/view.zoom});}else setView({...view,x:view.x-e.deltaX,y:view.y-e.deltaY});}}>
 <div className="flow-world" style={{transform:`translate(${view.x}px,${view.y}px) scale(${view.zoom})`}}><svg className="flow-connections"><defs><marker id={marker} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor"/></marker></defs>{flow.edges.map(e=>{const a=nodes.find(n=>n.id===e.from),b=nodes.find(n=>n.id===e.to);if(!a||!b)return null;const c=curve(a,b,e.action==='repeat');return <g key={e.id} className={'flow-edge '+(selected===e.id?'active':'')} onClick={()=>setSelected(e.id)}><path className="edge-hit" d={c.path}/><path className="edge-line" d={c.path} markerEnd={`url(#${marker})`}/></g>;})}</svg>
 {flow.edges.map(e=>{const a=nodes.find(n=>n.id===e.from),b=nodes.find(n=>n.id===e.to);if(!a||!b)return null;const c=curve(a,b,e.action==='repeat');return <button key={e.id} className={'flow-edge-label '+(selected===e.id?'active':'')} style={{left:c.lx,top:c.ly}} onClick={()=>setSelected(e.id)}>{e.title||e.action}{e.trigger&&<small>Click: {e.trigger.name||e.trigger.elementId}</small>}</button>;})}
 {nodes.filter(n=>n.x+260>=-view.x/view.zoom-120&&n.y+260>=-view.y/view.zoom-120&&n.x<((canvas.current?.clientWidth||1200)-view.x)/view.zoom+120&&n.y<((canvas.current?.clientHeight||800)-view.y)/view.zoom+120).map(n=><article key={n.id} tabIndex={0} aria-label={'Flow step '+n.title} className={'flow-step kind-'+n.kind+(selected===n.id?' selected':'')+(connecting?' connecting':'')} style={{left:n.x,top:n.y}} onPointerDown={e=>start(e,n)} onPointerMove={move} onPointerUp={finish} onPointerCancel={e=>finish(e,true)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();pick(n);}}}><small>{symbols[n.kind]} {n.kind==='frame'?'LINKED FRAME':n.kind==='end'?'END STATE':n.kind.toUpperCase()}</small><strong>{n.title}</strong>{n.reference&&<FrameThumbnail reference={n.reference} api={api}/>}<p>{n.explanation|| (n.kind==='frame'?'Reference to an existing design':n.kind==='if'?'Connect Yes / No branches':n.kind==='repeat'?'Add a loop condition':'Describe the final result')}</p>{n.reference&&<a href={flowLink(n.reference)} target="_blank" rel="noreferrer">Open frame ↗</a>}{n.kind!=='end'&&<button className="flow-port output" aria-label={'Connect from '+n.title} disabled={busy} onClick={()=>{setSelected(n.id);setConnecting(n.id);}}>＋</button>}<button className="flow-port input" aria-label={'Connect to '+n.title} disabled={!connecting||busy} onClick={()=>connecting&&connect(connecting,n.id)}>•</button></article>)}</div>
 {!nodes.length&&<div className="flow-empty"><span>↗</span><h2>Connect your screens.</h2><p>Add existing frames, decisions, loops and end states.<br/>Then connect them into a product journey.</p><button className="primary-button" disabled={!board} onClick={()=>setPicker('add')}>Add your first frame</button>{!board&&<button onClick={onNewBoard}>Create a flow board</button>}</div>}<div className="flow-canvas-hint">{connecting?'Click an input port or another step to connect · Esc cancels':'Drag steps · Drag empty canvas to pan · Ctrl + scroll to zoom · Ctrl+Z to undo'}</div></div></main>
 <SidePanel {...panelProps('right')}><aside className="flow-inspector"><div className="flow-section-heading">{edge?'TRANSITION':node?'STEP':'FLOW DETAILS'} <span>r{board?.revision||0}</span></div>{item?<div className="flow-properties" key={item.id}><h2>{node?symbols[node.kind]:'↗'} {item.title||item.action}</h2><EditField label="Flow title" value={item.title} disabled={busy} onSave={title=>patch({title})}/><EditField label="Flow explanation" value={item.explanation} multiline disabled={busy} onSave={explanation=>patch({explanation})}/>{edge?<TransitionFields {...{edge,nodes,api}} disabled={busy} onPatch={patch}/>:<><div className="flow-position"><EditField label="Flow X" value={String(node.x)} disabled={busy} onSave={x=>patch({x:Number(x)})}/><EditField label="Flow Y" value={String(node.y)} disabled={busy} onSave={y=>patch({y:Number(y)})}/></div>{node.reference&&<><ReferenceInfo reference={node.reference} api={api}/><button className="panel-action" disabled={busy} onClick={()=>setPicker('replace')}>Change referenced frame</button></>}{node.kind!=='end'&&<button className="panel-action" disabled={busy} onClick={()=>setConnecting(node.id)}>Connect this step →</button>}{node.kind==='end'&&<p>Final state. Give this outcome a title and explanation. It has no outgoing transitions.</p>}</>}<button className="danger-action" disabled={busy} onClick={remove}>Delete {node?'step':'transition'}</button></div>:<div className="flow-properties"><h2>Flows</h2><p>Select a step or arrow to edit its title, explanation and action.</p><ol><li>Add a frame from your designs.</li><li>Add If, Repeat or End steps.</li><li>Select a step, choose Connect, and click the next step.</li><li>Choose an arrow to link its source button and describe what happens.</li></ol><p>Flows are diagrams for design and implementation. They do not execute the application.</p></div>}{error&&<p className="flow-error" role="alert">{error}</p>}<footer className="flow-storage"><button onClick={onTask}>{board?.taskRef||'Link a task'}</button><button disabled={!board} onClick={onExport}>Export .free</button><code>{board?.filePath}</code></footer></aside></SidePanel>
 {picker&&<FramePicker {...{api,workspaces,busy}} onClose={()=>setPicker(false)} onChoose={reference=>picker==='replace'?action([{op:'updateNode',id:node.id,patch:{reference}}],'Change frame reference').then(result=>{if(result)setPicker(false);}):add('frame',reference)}/>}</>;
}
