import React,{useRef,useState} from 'react';
import {Icon} from './icons.jsx';
import {symbolBounds,FLOW_SYMBOLS} from '../shared/flow-overlay.mjs';
export function FlowSymbol({symbol,viewport,busy,highlight,onEdit,onMove,onPreviewMove}){
 const gesture=useRef(null),moved=useRef(false),position=useRef(null),[draft,setDraft]=useState(null),[error,setError]=useState('');const bounds=symbolBounds(symbol),p=draft||symbol;
 function reset(){position.current=null;setDraft(null);onPreviewMove(symbol.id,null);}
 function finish(e,cancel=false){const g=gesture.current;if(!g)return;gesture.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);const result=position.current;if(cancel||!moved.current||!result){reset();return;}Promise.resolve(onMove(symbol.id,result)).catch(err=>setError(err.message)).finally(reset);}
 return <div className={'flow-symbol '+(highlight?'flow-symbol-active':'')} data-flow-symbol={symbol.id} style={{left:p.x,top:p.y,width:bounds.width,height:bounds.height}} onPointerDown={e=>{e.stopPropagation();if(e.button!==0||busy)return;moved.current=false;position.current=null;gesture.current={x:e.clientX,y:e.clientY,before:{x:symbol.x,y:symbol.y}};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const g=gesture.current;if(!g)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(Math.hypot(dx,dy)<3&&!moved.current)return;moved.current=true;const next={x:g.before.x+dx/viewport.zoom,y:g.before.y+dy/viewport.zoom};position.current=next;setDraft(next);onPreviewMove(symbol.id,next);}} onPointerUp={e=>finish(e)} onPointerCancel={e=>finish(e,true)} onDoubleClick={e=>e.stopPropagation()} onClick={()=>{if(moved.current){moved.current=false;return;}onEdit(symbol);}}>
 <button className="flow-symbol-shape" disabled={busy} aria-label={symbol.kind+': '+symbol.title} title={symbol.title+' · '+symbol.explanation+' · Drag to move; click to edit'} onKeyDown={e=>{const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(delta&&!busy){e.preventDefault();e.stopPropagation();onMove(symbol.id,{x:symbol.x+delta[0]*(e.shiftKey?1:10),y:symbol.y+delta[1]*(e.shiftKey?1:10)}).catch(err=>setError(err.message));}}}><svg viewBox="0 0 64 64" aria-hidden="true">{symbol.kind==='decision'?<path d="M32 2L62 32L32 62L2 32Z"/>:symbol.kind==='start'?<circle cx="32" cy="32" r="28" className="flow-symbol-dot"/>:<><circle cx="32" cy="32" r="29"/><circle cx="32" cy="32" r="20" className="flow-symbol-dot"/></>}</svg></button><span className="flow-symbol-title">{symbol.title}</span>{error&&<span role="alert" className="flow-symbol-error">{error}</span>}
 </div>;
}
export function FlowSymbolEditor({symbol,existing,busy,onSave,onRemove,onClose}){
 const [draft,setDraft]=useState(symbol),[saving,setSaving]=useState(false),[error,setError]=useState('');async function save(remove=false){setSaving(true);setError('');try{await (remove?onRemove():onSave(draft));onClose();}catch(e){setError(e.message);}finally{setSaving(false);}}
 return <div className="dialog-backdrop flow-overlay-dialog" onPointerDown={e=>e.stopPropagation()} onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)onClose();}}><form className="studio-dialog" role="dialog" aria-label="Flow symbol editor" onSubmit={e=>{e.preventDefault();save();}}><div className="dialog-title"><h2>{existing?'Edit':'Add'} flow symbol</h2><button type="button" aria-label="Close flow symbol editor" disabled={saving} onClick={onClose}><Icon name="close"/></button></div><p>Start dots, decision diamonds and end markers belong to the flow layer. Use existing design frames for page steps. Removing a symbol also removes its connected arrows; Ctrl+Z restores them together.</p><label>Symbol<select aria-label="Symbol type" value={draft.kind} disabled={saving} onChange={e=>setDraft({...draft,kind:e.target.value})}>{FLOW_SYMBOLS.map(kind=><option key={kind} value={kind}>{kind[0].toUpperCase()+kind.slice(1)}</option>)}</select></label><label>Title<input aria-label="Symbol title" required maxLength={160} value={draft.title} disabled={saving} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Description<textarea aria-label="Symbol description" maxLength={10000} rows={3} value={draft.explanation} disabled={saving} onChange={e=>setDraft({...draft,explanation:e.target.value})}/></label><div className="flow-symbol-position">{['x','y'].map(axis=><label key={axis}>{axis.toUpperCase()}<input type="number" aria-label={'Symbol '+axis.toUpperCase()} required min={-100000} max={100000} step="any" value={draft[axis]} disabled={saving} onChange={e=>setDraft({...draft,[axis]:e.target.value===''?'':Number(e.target.value)})}/></label>)}</div>{error&&<p role="alert" className="palette-error">{error}</p>}<div className="dialog-actions">{existing&&<button type="button" className="danger-action" disabled={busy||saving} onClick={()=>save(true)}><Icon name="trash" size={14}/>Remove symbol</button>}<button type="button" disabled={saving} onClick={onClose}>Cancel</button><button type="submit" className="primary-button" disabled={busy||saving}>{saving?'Saving…':'Save symbol'}</button></div></form></div>;
}
