import React,{useState,useRef,useEffect,useMemo} from 'react';
import {layerStyle} from '../shared/design.mjs';
import {belongsToFrame} from '../shared/flow-overlay.mjs';
import {flowLink} from '../shared/flows.mjs';
import {Icon} from './icons.jsx';
function ReferenceLayer({node,parent,children,highlight,path}){
 return <div data-flow-element={node.id} className={'design-layer '+(highlight===node.id?'flow-trigger-highlight ':'')+(path.has(node.id)?'flow-highlight-path':'')} style={layerStyle(node,parent,!parent)}>{node.type==='text'&&node.text}{node.type==='image'&&node.src&&<img src={node.src} alt={node.name} loading="lazy"/>}{node.type==='icon'&&<Icon name={node.icon} size="100%"/>}{node.type==='vector'&&<svg viewBox={node.viewBox.join(' ')} width="100%" height="100%">{node.paths.map((p,i)=><path key={i} {...p}/>)}</svg>}{(children.get(node.id)||[]).map(n=><ReferenceLayer key={n.id} node={n} parent={node} children={children} highlight={highlight} path={path}/>)}</div>;
}
export function FlowReferenceFrame({frame,viewport,api,busy,highlight,onRemove,onMove,onPreviewMove,onLoaded,title,onSelect}){
 const [preview,setPreview]=useState(null),[error,setError]=useState(''),[draft,setDraft]=useState(null),gesture=useRef(null);
 useEffect(()=>{let active=true,revision='',loading=false;setPreview(null);setError('');const load=async()=>{if(loading)return;loading=true;try{const data=await api(`/api/boards/${frame.reference.boardId}/flow-preview?frameId=${frame.reference.frameId}`);if(active){revision=[data.revision,data.paletteRevision,data.themeId].join(':');setPreview(data.document);setError('');onLoaded(frame.id,data.document);}}catch(e){if(active){setError(e.message);setPreview(null);onLoaded(frame.id,null);}}finally{loading=false;}};load();const timer=setInterval(async()=>{if(document.hidden||loading)return;try{const status=await api(`/api/boards/${frame.reference.boardId}/status`);if(active&&[status.revision,status.paletteRevision,status.themeId].join(':')!==revision)load();}catch(e){if(active){setError(e.message);setPreview(null);onLoaded(frame.id,null);}}},5000);return()=>{active=false;clearInterval(timer);};},[frame.reference.boardId,frame.reference.frameId]);
 const nodes=preview?.nodes||[],root=nodes[0],children=useMemo(()=>{const map=new Map();for(const n of nodes){if(!map.has(n.parentId))map.set(n.parentId,[]);map.get(n.parentId).push(n);}return map;},[preview]);
 const nodeMap=useMemo(()=>new Map(nodes.map(n=>[n.id,n])),[preview]),path=useMemo(()=>new Set(highlight?nodes.filter(n=>belongsToFrame(nodeMap,highlight,n.id)).map(n=>n.id):[]),[preview,highlight]);
 const position=draft||frame;
 function end(event,cancel=false){const g=gesture.current;if(!g)return;gesture.current=null;event.currentTarget.releasePointerCapture(event.pointerId);const result=draft;if(cancel||!result||result.x===frame.x&&result.y===frame.y){setDraft(null);onPreviewMove(frame.id,null);return;}Promise.resolve(onMove(frame.id,result)).catch(e=>setError(e.message)).finally(()=>{setDraft(null);onPreviewMove(frame.id,null);});}
 return <div className="flow-reference-frame" data-flow-frame={frame.id} style={{left:position.x,top:position.y,width:root?.width||frame.width,height:root?.height||frame.height}} onPointerDown={e=>{e.stopPropagation();onSelect?.();}} onDoubleClick={e=>e.stopPropagation()}>
  <div className="flow-reference-caption" onPointerDown={e=>{if(e.target.closest('button,a')||busy||e.button!==0)return;gesture.current={x:e.clientX,y:e.clientY,before:{x:frame.x,y:frame.y}};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const g=gesture.current;if(!g)return;const next={x:g.before.x+(e.clientX-g.x)/viewport.zoom,y:g.before.y+(e.clientY-g.y)/viewport.zoom};setDraft(next);onPreviewMove(frame.id,next);}} onPointerUp={e=>end(e)} onPointerCancel={e=>end(e,true)}><Icon name="lock" size={14}/><strong>{title||root?.name||frame.reference.name||'Linked frame'}</strong><span title="Locked master reference · edit in the original workspace">Locked master</span><a href={flowLink(frame.reference)} target="_blank" rel="noreferrer" title="Edit original frame">↗</a><button disabled={busy} aria-label={'Remove frame reference '+(root?.name||frame.reference.name||'Linked frame')} onClick={()=>onRemove(frame.id)}><Icon name="close" size={14}/></button></div>
  {root?<ReferenceLayer node={{...root,x:0,y:0,parentId:null}} children={children} highlight={highlight===frame.id?root.id:highlight} path={path}/>:<div className="flow-reference-missing">{error||'Loading original design…'}<a href={flowLink(frame.reference)} target="_blank" rel="noreferrer">Open original ↗</a></div>}
 </div>;
}
