import React,{useState} from 'react';
import {projectColors} from '../shared/project-template.mjs';
import {Icon} from './icons.jsx';

export function ProjectGuide({onClose,onCreate}){
  const [mode,setMode]=useState('dark'),palette=projectColors(),colors=palette.themes.find(t=>t.id==='theme_'+mode).colors;
  return <main className="project-guide" aria-label="Folders and themes guide">
    <div className="guide-content"><header className="guide-header"><div><span className="guide-eyebrow">FREEGMA · QUICK GUIDE</span><h1>One library. Multiple themes.</h1><p>Organize the project once. Change its colors without duplicating components.</p></div><button className="quiet-button" onClick={onClose}><Icon name="close" size={16}/>Back to editor</button></header>
    <div className="guide-grid"><section className="guide-card"><h2><Icon name="folder"/>Folders & shared components</h2><div className="guide-tree"><strong>My project</strong><span>├ Shared library: Button, Card, Navigation</span><span>├ Shared boards: Dashboard, Settings</span><span>├ Light Mode <small>optional extras</small></span><span>└ Dark Mode <small>optional extras</small></span></div><p>Save common components in the parent project’s Assets library. They appear in every child folder. No Components subfolder needed.</p><p>Keep a theme-only component in its own folder—for example, a Dark Mode glow effect. Siblings won’t see that local extra.</p></section>
    <section className="guide-card"><h2><Icon name="grid"/>Color schematic & themes</h2><p>The schematic defines roles such as Background, Surface and Text. Each theme supplies its own values for those same roles.</p><table className="guide-colors"><thead><tr><th>Role</th><th>Light Mode</th><th>Dark Mode</th></tr></thead><tbody>{palette.schematic.slice(0,7).map(role=><tr key={role.key}><th>{role.name}</th>{palette.themes.map(theme=><td key={theme.id}><i style={{background:theme.colors[role.key]}}/><code>{theme.colors[role.key].toUpperCase()}</code></td>)}</tr>)}</tbody></table><p>In the inspector, choose a <strong>Color role</strong> for a fill, border or text color. Keep <strong>Local color</strong> for an exact value that should stay the same in every theme.</p></section></div>
    <section className="guide-card guide-example"><div><span className="guide-eyebrow">TRY THE SAME COMPONENT</span><h2>One Card. Two palettes.</h2><p>These controls only change this example. Your saved project colors stay intact.</p><div className="guide-theme-switch" role="group" aria-label="Example theme">{['light','dark'].map(value=><button key={value} aria-pressed={mode===value} onClick={()=>setMode(value)}>{value==='light'?'Light Mode':'Dark Mode'}</button>)}</div><p>A role-linked Card changes with the theme. The pink dot uses a local color and stays pink.</p></div><div className="guide-preview" style={{background:colors.background}}><article style={{background:colors.surface,color:colors.text,borderColor:colors.border}}><span className="guide-local-dot"/><h3>Your next idea</h3><p style={{color:colors.muted}}>Same layout, spacing and content. Different color values.</p><span className="guide-demo-button" style={{background:colors.accent,color:colors.on_accent}}>Create something</span></article></div></section>
    <section className="guide-card"><h2>Follow the component reference</h2><p><strong>Master</strong> in Layers means the source you edit. <strong>Instance</strong> means a linked use. Select either, or one of its child layers, to see the component name, owning project, ID and usage count in <strong>Component reference</strong>.</p><p>Use <strong>Go to main component</strong> to open its source board and select the master. <strong>Show linked usages</strong> opens any instance. Edit the master’s padding or corner radius once: every non-overridden instance updates, including Light and Dark folders. Instances show a lock and remain browsable. Click the lock beside Text content to enable only that override, then change its label. The orange warning marks a local value kept on master updates; Reset follows the latest master again. All property overrides also supports each CSS declaration separately. <strong>Detach instance</strong> makes it independent.</p><p>A template is an independent starting copy. Insert from <strong>Assets → Components</strong> when you need reuse.</p></section><section className="guide-card"><h2>Start in five steps</h2><ol className="guide-steps"><li><strong>New project → Light & Dark template.</strong> Get shared Button/Card masters, an example board, both palettes and theme folders. Choose Empty for a blank board.</li><li><strong>Open Shared components.</strong> Edit the Button or Card master. Saved edits automatically update instances in parent and child boards; local overrides remain.</li><li><strong>Open Example dashboard → Colors.</strong> Choose Design theme → Light Mode or Dark Mode. This switches the same board, without copying components.</li><li><strong>Add roles or themes as needed.</strong> A new role appears in every palette. A new theme copies the current theme’s full schematic before you edit its values.</li><li><strong>Use folders for exceptions.</strong> New workspace or New parent folder organizes extra boards and local components. Export the parent .free to include all children; Copy link opens an exact board.</li></ol><div className="guide-actions"><button className="primary-button" onClick={onCreate}><Icon name="plus" size={16}/>Create a project</button><p>Editor Dark / Light in the header changes the editor’s appearance. Colors → Design theme changes the artwork.</p></div></section>
    </div>
  </main>;
}
