// Local client-state timings, separate from paint/render and server durability.
// Capture the old running local build before replacing it. No public requests.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';import {createBoardCache} from '../../client/board-cache.mjs';import {applyOptimisticEdit} from '../../client/optimistic-edits.mjs';
const origin=process.argv[2]||'http://127.0.0.1:4338',folder=path.resolve(process.argv[3]||'logs/browser-cache-20261002'),url=new URL(origin);if(!['127.0.0.1','localhost','[::1]'].includes(url.hostname))throw Error('Local tests only.');fs.mkdirSync(folder,{recursive:true});
const fixture=JSON.parse(fs.readFileSync('logs/performance-20261001/fixture/fixture.json')),request=async(route,method='GET',body)=>{const t=performance.now(),r=await fetch(origin+route,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(30000)}),bytes=Buffer.from(await r.arrayBuffer());if(!r.ok)throw Error(bytes.toString());return {board:JSON.parse(bytes),ms:performance.now()-t,bytes:bytes.length};};
const baselineFile=path.join(folder,'navigation-baseline.json');if(!fs.existsSync(baselineFile)){const health=(await request('/api/health')).board,reads=[],undo=[];for(let i=0;i<15;i++)reads.push(await request('/api/boards/'+fixture.designBoard));let flow=(await request('/api/boards/'+fixture.flowBoard)).board;const before=flow.document;for(let i=0;i<12;i++){const result=await request('/api/boards/'+flow.id+'/undo','POST',{expectedRevision:flow.revision,expectedPaletteRevision:flow.palette.revision});undo.push({ms:result.ms,bytes:result.bytes});flow=(await request('/api/boards/'+flow.id+'/redo','POST',{expectedRevision:result.board.revision,expectedPaletteRevision:result.board.palette.revision})).board;}assert.deepEqual(flow.document,before);fs.writeFileSync(baselineFile,JSON.stringify({capturedAt:new Date().toISOString(),version:health.version,scope:'Warm local HTTP response fully parsed; excludes React paint. Undo/Redo pairs restored original synthetic flow.',read:reads.map(({ms,bytes})=>({ms,bytes})),undo},null,2),{flag:'wx'});}
const design=(await request('/api/boards/'+fixture.designBoard)).board,flow=(await request('/api/boards/'+fixture.flowBoard)).board;let requests=0;const cache=createBoardCache({apply:applyOptimisticEdit,onBoard:()=>{},send:async()=>{requests++;throw Error('State-only measurement does not save.');}});cache.activate(design);cache.activate(flow);const back=[];for(let i=0;i<15;i++){cache.activate(flow);const t=performance.now();cache.activate(cache.get(design.id).board);back.push({ms:performance.now()-t,bytes:0});assert.equal(cache.board,design);}
cache.activate(flow);const startX=flow.document.flow.nodes.find(n=>n.id==='step_0').x;cache.enqueue({kind:'flow',label:'Measured complete move',operations:[{op:'updateNode',id:'step_0',patch:{x:startX+1}}]});const undo=[];for(let i=0;i<12;i++){const t=performance.now();cache.history('undo');undo.push({ms:performance.now()-t,bytes:0});assert.equal(cache.board.document.flow.nodes.find(n=>n.id==='step_0').x,startX);cache.history('redo');}cache.dispose();assert.equal(requests,0);
const baseline=JSON.parse(fs.readFileSync(baselineFile)),median=a=>[...a].sort((x,y)=>x.ms-y.ms)[Math.floor(a.length/2)].ms,result={date:new Date().toISOString(),scope:'Client state restoration only; excludes React paint and eventual background-save time.',samples:{back,undo},metrics:{backBeforeMs:median(baseline.read),backAfterMs:median(back),undoBeforeMs:median(baseline.undo),undoAfterMs:median(undo),restoreDocumentBytesBefore:baseline.read[0].bytes,restoreDocumentBytesAfter:0,historyRestoreBytesBefore:baseline.undo[0].bytes,historyRestoreBytesAfter:0},notes:'Cached restores issue no network request. Revision checks and later history saves still transfer data.'};const out=path.join(folder,'navigation-round-01.json');if(fs.existsSync(out))throw Error('Preserve previous measurements; select a new folder.');fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify({...result,samples:undefined},null,2));
