import fs from 'node:fs';import path from 'node:path';
const label=process.argv[2],root=path.resolve('logs/startup-20261002');if(!/^round-\d+$/.test(label||''))throw Error('Supply a startup run label.');
const baseline=JSON.parse(fs.readFileSync(path.join(root,'baseline.json'))),current=JSON.parse(fs.readFileSync(path.join(root,label+'.json')));
if(JSON.stringify(baseline.fixture)!==JSON.stringify(current.fixture)||baseline.samples.length!==current.samples.length)throw Error('Different startup workloads.');
for(let i=0;i<baseline.samples.length;i++)for(const key of ['designDigest','flowDigest'])if(baseline.samples[i][key]!==current.samples[i][key])throw Error('Viewed content changed.');
const median=(data,key)=>data.samples.map(s=>s[key]).sort((a,b)=>a-b)[Math.floor(data.samples.length/2)],number=n=>n.toLocaleString('en-US',{maximumFractionDigits:2});
const rows=Object.entries({startupMs:'Cold indexing',firstViewMs:'First design view after indexing',startupAndFirstViewMs:'Indexing + first design view',secondViewMs:'First flow view after design',boardsDecodedAtStartup:'Boards decoded during indexing',boardsDecodedAfterFirstView:'Boards decoded after first design view'}).map(([key,name])=>{const before=median(baseline,key),after=median(current,key),unit=key.endsWith('Ms')?'ms':'boards';return {key,name,before,after,unit,change:before?(after/before-1)*100:null};});
const md=`Local startup comparison · ${label}\n\nFrozen v${baseline.version} baseline ${baseline.commit}. Three fresh isolated stores; exact viewed design/flow digests verified. First view includes workspace catalog, selected workspace board catalog and board read. Deferred work is included in the combined row. These rows are bold because they describe this optimization. Full request/UI/network/file/MCP comparisons remain separate.\n\n| Measurement | Before snapshot | Current | Change |\n| --- | ---: | ---: | ---: |\n`+rows.map(r=>`| **${r.name}** | **${number(r.before)} ${r.unit}** | **${number(r.after)} ${r.unit}** | **${r.change==null?'—':number(r.change)+'%'}** |`).join('\n')+'\n';
fs.writeFileSync(path.join(root,label+'-comparison.md'),md);fs.writeFileSync(path.join(root,label+'-comparison.json'),JSON.stringify({baselineVersion:baseline.version,currentVersion:current.version,localOnly:true,rows},null,2));console.log(md);
