import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(process.argv[2]||'logs/performance-20261001'),label=process.argv[3];if(!label||!/^[a-z0-9-]+$/.test(label))throw Error('Supply the directory and measured run label.');
const base=JSON.parse(fs.readFileSync(path.join(root,'baseline.json'),'utf8')),current=JSON.parse(fs.readFileSync(path.join(root,label+'.json'),'utf8'));
if(JSON.stringify(base.fixture)!==JSON.stringify(current.fixture))throw Error('Different fixtures cannot be compared.');
const rows=[],number=n=>n.toLocaleString('en-US',{maximumFractionDigits:2});
function row(name,a,b,unit){rows.push(`| ${name} | ${number(a)} ${unit} | ${number(b)} ${unit} | ${a?number((b/a-1)*100)+'%':'—'} |`);}
row('Cold startup',base.metrics.coldStartupMs,current.metrics.coldStartupMs,'ms');
for(const [key,name] of Object.entries({designRead:'Design read',boardStatus:'Unchanged board status',workspaceCatalog:'Workspace list',boardCatalog:'Board list',framePreview:'Frame preview',flowRead:'Flow read',designSave:'Completed design save',unchangedSave:'Unchanged action',flowSave:'Completed flow save'})){
 const a=base.metrics[key],b=current.metrics[key];if(a.n!==b.n)throw Error('Sample counts differ for '+key);
 row(name+' · median',a.medianMs,b.medianMs,'ms');row(name+' · p95',a.p95Ms,b.p95Ms,'ms');row(name+' · response',a.responseBytes,b.responseBytes,'B');
}
row('Design file after fixed save sequence',base.metrics.designFileBytes,current.metrics.designFileBytes,'B');
// Size baselines added later have their own frozen capture, never an invented value.
if(process.argv[4]){const sizes=JSON.parse(fs.readFileSync(path.resolve(process.argv[4]),'utf8'));for(const [key,name] of Object.entries({designFixture:'Initial design .free (size snapshot)',flowFixture:'Initial flow .free (size snapshot)',workspaceManifests:'Workspace .free manifests (size snapshot)',portableExamples:'Portable example .free downloads (size snapshot)',assets:'Original assets (size snapshot)',sqliteIndex:'SQLite index/WAL (volatile size snapshot)',productionBuild:'Production editor build (size snapshot)',source:'Product source (size snapshot)',readmeMedia:'README media (size snapshot)',developmentDependencies:'Development dependencies (size snapshot)'})){const r=sizes.totals[key];if(r)row(name,r.before,r.after,'B');}}
if(process.argv[5]){const mcp=JSON.parse(fs.readFileSync(path.resolve(process.argv[5]),'utf8'));for(const [key,name]of Object.entries({toolDefinitions:'Tool definitions',designRead:'Selected design frame read',designMutation:'Design edit receipt',flowRead:'Selected flow step read',flowMutation:'Flow edit receipt',workflowTokens:'Workflow total'})){const r=mcp.totals[key];row('MCP '+name+' (token snapshot)',r.before,r.after,'tokens');}const r=mcp.totals.workflowBytes;row('MCP workflow payload (token snapshot)',r.before,r.after,'B');}
if(process.argv[6]){const transfer=JSON.parse(fs.readFileSync(path.resolve(process.argv[6]),'utf8'));for(const r of Object.values(transfer.totals))row('Encoded HTTP '+r.name+' (v'+transfer.baselineVersion+' transfer snapshot)',r.before,r.after,'B');}
const text=`Local-only performance comparison · ${label}\n\nBaseline: ${base.commit}. Current: ${current.commit}. Fixed fixture and sample counts verified. Negative percentages indicate reductions. File-size rows marked “size snapshot” use the separately captured 0.1.31 baseline because they were absent from the original 0.1.26 run. MCP rows use the frozen local v0.1.35 snapshot and fixed o200k_base tokenizer; text plus structured content is counted, so client rendering and actual billing may differ. They compare the same task using full board reads/receipts before and scoped reads/compact receipts after. HTTP body bytes exclude headers; browser idle traffic is recorded separately. Local absolute file-path metadata varies with the benchmark output directory; tiny response-size differences from those paths do not represent design-content growth. Warm reads and cold startup are separate workloads.\n\n| Measurement | Original baseline / size snapshot | Current | Change |\n| --- | ---: | ---: | ---: |\n${rows.join('\n')}\n`;
fs.writeFileSync(path.join(root,label+'-comparison.md'),text);console.log(text);
