import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {decodeFree,encodeFree} from '../../server/free-format.mjs';
const root=path.resolve(process.argv[2]||'logs/file-size-20261002'),label=process.argv[3]||'round-01',output=path.join(root,label+'.json');if(!/^[a-z0-9-]+$/.test(label)||fs.existsSync(output))throw Error('Preserve previous size runs; use a new label.');
const base=JSON.parse(fs.readFileSync(path.join(root,'codec-baseline.json'))),inventory=JSON.parse(fs.readFileSync(path.join(root,'baseline-inventory.json'))),folder=path.join(root,label);fs.mkdirSync(folder,{recursive:true});const rows=[];
for(const entry of base.rows){const source=fs.readFileSync(path.join(root,'before',path.basename(entry.file))),value=decodeFree(source).value,encoded=encodeFree(value),file=path.join(folder,path.basename(entry.file));fs.writeFileSync(file,encoded,{flag:'wx'});const read=fs.readFileSync(file);assert.deepEqual(decodeFree(read).value,value);rows.push({file:entry.file,before:source.length,after:read.length,logicalSha256:createHash('sha256').update(JSON.stringify(value)).digest('hex'),exactContentVerified:true});}
const size=dir=>fs.existsSync(dir)?fs.readdirSync(dir,{withFileTypes:true}).reduce((n,e)=>n+(e.isDirectory()?size(path.join(dir,e.name)):e.isFile()?fs.statSync(path.join(dir,e.name)).size:0),0):0;
const fixture=path.join(path.resolve(base.fixtureRoot||'logs/performance-20261001/fixture'),'workspaces'),manifests=[];
for(const w of fs.readdirSync(fixture,{withFileTypes:true}).filter(e=>e.isDirectory()&&e.name.startsWith('workspace_'))){const file=path.join(fixture,w.name,w.name+'.free'),bytes=fs.readFileSync(file),value=decodeFree(bytes).value,encoded=encodeFree(value);assert.deepEqual(decodeFree(encoded).value,value);manifests.push({before:bytes.length,after:encoded.length});}
const sum=(arr,key)=>arr.reduce((n,r)=>n+r[key],0),examples=rows.filter(r=>r.file.startsWith('examples/'));
const baselinePathsSize=files=>files.reduce((n,f)=>n+(fs.existsSync(f.path)?fs.statSync(f.path).size:0),0);
const totals={designFixture:rows[0],flowFixture:rows[1],workspaceManifests:{before:sum(manifests,'before'),after:sum(manifests,'after')},portableExamples:{before:sum(examples,'before'),after:fs.readdirSync('examples').filter(f=>f.endsWith('.free')).reduce((n,f)=>n+fs.statSync(path.join('examples',f)).size,0)},assets:{before:inventory.totals.assets.bytes,after:baselinePathsSize(inventory.files.assets)},sqliteIndex:{before:inventory.totals.sqlite.bytes,after:baselinePathsSize(inventory.files.sqlite)},productionBuild:{before:inventory.totals.build.bytes,after:size(process.env.FREEGMA_BUILD||'dist')},readmeMedia:{before:inventory.totals.readmeMedia.bytes,after:size('docs/media')},source:{before:inventory.totals.source.bytes,after:['client','server','shared','scripts','tests'].reduce((n,dir)=>n+size(dir),0)},developmentDependencies:{before:inventory.totals.developmentDependencies.bytes,after:size('node_modules')}};
const archived=Object.values(inventory.files).flat().filter(f=>f?.path?.includes('/.trash/')),active=inventory.files.boardFree.filter(f=>!f.path.includes('/.trash/'));
const result={date:new Date().toISOString(),commit:process.env.FREEGMA_PERF_COMMIT||'working-tree',baselineCommit:base.commit,rows,totals,inventoryScope:{activeBoardFiles:active.length,activeBoardBytes:sum(active,'bytes'),recoverableTrashFiles:archived.length,recoverableTrashBytes:sum(archived,'bytes'),assetsBaselineBytes:inventory.totals.assets.bytes,note:'Live inventory is separate from fixed before/after fixtures. Archives, original images and SQLite are preserved; user edits can change live totals.'}};
fs.writeFileSync(output,JSON.stringify(result,null,2),{flag:'wx'});
const mb=b=>(b/1e6).toFixed(3)+' MB',table=Object.entries(totals).map(([key,r])=>`| ${key} | ${mb(r.before)} | ${mb(r.after)} | ${((r.after/r.before-1)*100).toFixed(2)}% |`).join('\n');
const report=`File-size comparison · ${label}\n\nBefore: ${base.commit}. Bytes measured on local files. The same frozen native documents were encoded, written, reread and deeply compared, including all history. Fixture size includes the original pretty JSON; the performance table separately measures its completed-save compact JSON baseline. Assets retain original bytes; recovery archives and SQLite are not trimmed. Asset/index rows measure the baseline path set, and SQLite/WAL is volatile while users edit. Build/source/media/dependency totals are separate from .free content.\n\n| Measurement | Before snapshot | Current | Change |\n| --- | ---: | ---: | ---: |\n${table}\n\nActive board inventory before optimization: ${active.length} files, ${mb(sum(active,'bytes'))}. Recoverable archives: ${mb(sum(archived,'bytes'))}; preserved, not counted as savings.\n`;
fs.writeFileSync(path.join(root,label+'-comparison.md'),report);console.log(report);
