import fs from 'node:fs';import path from 'node:path';import {createFixtures} from './fixtures.mjs';
const root=path.resolve('.'),out=path.resolve(process.argv[2]||'logs/file-size-baseline'),fixtureRoot=path.resolve(process.argv[3]||'logs/performance-20261001/fixture');
if(fs.existsSync(path.join(out,'baseline-inventory.json'))||fs.existsSync(path.join(out,'codec-baseline.json')))throw Error('Baseline exists; use a new directory.');fs.mkdirSync(path.join(out,'before'),{recursive:true});
const scan=folder=>{if(!fs.existsSync(folder))return [];return fs.readdirSync(folder,{withFileTypes:true}).flatMap(e=>{if(e.isSymbolicLink())return [];const file=path.join(folder,e.name);if(e.isDirectory())return scan(file);if(!e.isFile())return [];const stat=fs.statSync(file);return [{path:path.relative(root,file).replaceAll('\\','/'),bytes:stat.size,modified:stat.mtime.toISOString()}];});};
const storage=scan('data'),example=scan('examples');
const categories={boardFree:storage.filter(f=>f.path.endsWith('.free')&&f.path.includes('/b/')),workspaceFree:storage.filter(f=>f.path.endsWith('.free')&&!f.path.includes('/b/')),assets:storage.filter(f=>f.path.includes('/Assets/')),sqlite:storage.filter(f=>/\.sqlite(?:-wal|-shm)?$/.test(f.path)),build:scan(process.env.FREEGMA_BUILD||'dist'),portableExamples:example.filter(f=>f.path.endsWith('.free')),readmeMedia:scan('docs/media'),source:['client','server','shared','scripts','tests'].flatMap(scan),developmentDependencies:scan('node_modules')};
const totals=Object.fromEntries(Object.entries(categories).map(([key,files])=>[key,{files:files.length,bytes:files.reduce((n,f)=>n+f.bytes,0)}]));
const fixture=createFixtures(fixtureRoot),files=[path.join(fixtureRoot,'workspaces',fixture.designWorkspace,'b',fixture.designBoard+'.free'),path.join(fixtureRoot,'workspaces',fixture.flowWorkspace,'b',fixture.flowBoard+'.free'),...categories.portableExamples.map(f=>f.path)],rows=[];
for(const file of files){const bytes=fs.readFileSync(file);fs.writeFileSync(path.join(out,'before',path.basename(file)),bytes,{flag:'wx'});rows.push({file:path.relative(root,file).replaceAll('\\','/'),bytes:bytes.length});}
const metadata={date:new Date().toISOString(),commit:process.env.FREEGMA_PERF_COMMIT||'working-tree',fixtureRoot};
fs.writeFileSync(path.join(out,'baseline-inventory.json'),JSON.stringify({...metadata,sourceCommit:metadata.commit,scope:'Read-only live inventory; fixed board/example bytes copied separately. SQLite/WAL is volatile. Logs and Git excluded.',totals,files:categories},null,2),{flag:'wx'});
fs.writeFileSync(path.join(out,'codec-baseline.json'),JSON.stringify({...metadata,fixture,rows},null,2),{flag:'wx'});console.log('Pinned file-size baseline: '+out);
