import test from 'node:test';import assert from 'node:assert/strict';
import {createBoardCache} from '../client/board-cache.mjs';import {applyOptimisticEdit} from '../client/optimistic-edits.mjs';import {makeNode} from '../shared/design.mjs';
const board=id=>({id,revision:1,palette:{revision:0},comments:[],document:{version:1,nodes:[makeNode('frame',{id:'frame'})]}}),move=x=>({kind:'design',label:'Move',operations:[{op:'update',id:'frame',patch:{x}}]}),bytes=b=>Buffer.byteLength(JSON.stringify(b));
function create(options={}){let cache;cache=createBoardCache({apply:applyOptimisticEdit,onBoard:()=>{},send:async r=>({...cache.board,revision:r.expectedRevision+1}),queueOptions:{setTimer:()=>1,clearTimer:()=>{},id:()=> 'batch-1'},...options});return cache;}
function countAccept(cache,value,method='accept'){const stringify=JSON.stringify;let count=0;try{JSON.stringify=function(v,...args){if(v?.document&&v.id===value.id)count++;return stringify.call(JSON,v,...args);};cache[method](value);}finally{JSON.stringify=stringify;}return count;}

test('one fresh whole-envelope sizing pass per activation and saved acceptance, with no long-lived weight reuse',async()=>{const c=create(),a=board('a');try{assert.equal(countAccept(c,a,'activate'),1);c.enqueue(move(10));await c.flush();const replacement={...c.board,name:'A 🟣 色',comments:[{text:'"quoted" \\ newline\n'}]};assert.equal(countAccept(c,replacement),1);replacement.comments.push({text:'Externally changed envelope'});assert.equal(countAccept(c,replacement),1);assert.equal(c.board.comments.length,2);assert.equal(c.state.phase,'saved');}finally{c.dispose();}});

test('exact UTF-8 envelope budget includes comments, palette and escaped metadata on replacement',()=>{const a=board('a'),b=board('b');a.comments=[{text:'🟣 色 é " \\ \n \ud800'}];a.palette.colors={text:'#12345678'};a.name='Fresh \u00e9';const limit=bytes(a)+bytes(b);for(const delta of [0,-1]){const c=create({limits:{boards:10,bytes:limit+delta,ttlMs:1000,dirtyBoards:8}});try{c.activate(a);c.activate(b);assert.equal(!!c.get('a'),delta===0);}finally{c.dispose();}}const small=board('a'),c=create({limits:{boards:10,bytes:bytes(small)+bytes(b)+10,ttlMs:1000,dirtyBoards:8}});try{c.activate(small);c.activate(b);c.accept(a);assert.equal(c.get('a'),null);assert.equal(c.board.id,'b');}finally{c.dispose();}});

test('reentrant saved-state acceptance leaves final envelope fresh and byte limits enforced',async()=>{let armed=false,nested;const c=create({onState:s=>{if(armed&&s.phase==='saved'){armed=false;c.accept(nested);}}});try{c.activate(board('a'));c.enqueue(move(10));await c.flush();const outer={...c.board,name:'Outer'},inner={...outer,name:'Inner',comments:[{text:'Nested accepted snapshot 🟣'}]};nested=inner;armed=true;c.accept(outer);assert.equal(c.board,inner);assert.equal(c.get('a').board,inner);assert.equal(c.anyPending,false);assert.equal(countAccept(c,inner),1);}finally{c.dispose();}});

test('dirty acceptance measures the retained draft, not a remote replacement, and old acknowledgements stay isolated',async()=>{const flights=[],views=[],c=create({send:r=>new Promise(resolve=>flights.push({r,resolve})),onBoard:b=>views.push(b)});try{c.activate(board('a'));c.enqueue(move(10));const draft=c.board,saving=c.flush();c.activate(board('b'));c.accept({...board('a'),comments:[{text:'Rejected stale reply'}]});assert.equal(c.get('a').board,draft);const publishedBeforeReply=views.length;flights[0].resolve({...draft,revision:2});await saving;assert.equal(c.board.id,'b');assert.equal(views.length,publishedBeforeReply);assert.equal(c.get('a').board.document.nodes[0].x,10);}finally{c.dispose();}});

test('count, expiry and dirty retention limits survive completed acceptance',()=>{let time=0;const c=create({now:()=>time,limits:{boards:2,bytes:100000,ttlMs:100,dirtyBoards:2}});try{c.activate(board('a'));c.enqueue(move(10));c.activate(board('b'));c.activate(board('c'));assert.equal(c.get('b'),null);time=101;assert.ok(c.get('a'));assert.equal(c.get('c').board.id,'c');assert.equal(c.draft.boards[0].boardId,'a');c.deactivate();time=202;assert.equal(c.get('c'),null);assert.ok(c.get('a'));}finally{c.dispose();}});

