import test from 'node:test';
import assert from 'node:assert/strict';
import {FreegmaStore} from '../server/store.mjs';
import {makeNode} from '../shared/design.mjs';
import {flowAnchor,overlayPath,draggedFlowRoute,translatedFlowRoute} from '../shared/flow-route.mjs';
import {flowGraph,computeFlowLayout,applyLayout} from '../server/arrange-store.mjs';
import {callTool,rpc} from '../server/tools.mjs';
import {createServer} from '../server/http.mjs';
const edge=(id,fromFrameId,toFrameId,action='straight')=>({id,fromFrameId,toFrameId,action,title:id,explanation:'Preserve this explanation',event:'click'});
function fixture(){const s=new FreegmaStore(':memory:',{seed:false}),w=s.createWorkspace('Arrange test'),a=makeNode('frame',{id:'a',x:0,y:60,width:320,height:500,name:'Home'}),b=makeNode('frame',{id:'b',x:100,y:180,width:430,height:680,name:'Next'}),caption=makeNode('text',{id:'caption',x:0,y:20,width:320,height:32,text:'Home screen'}),child=makeNode('text',{id:'child',parentId:'a',x:20,y:100,text:'Editable content',colorBindings:[{path:'color',token:'text',source:'#172033'}]}),doc={version:1,nodes:[a,b,caption,child],flowOverlay:{version:1,edges:[{...edge('continue','a','b'),triggerId:'child'},edge('again','b','a','repeat')],symbols:[{id:'decision',kind:'decision',title:'Allowed?',explanation:'Condition',x:30,y:40},{id:'end',kind:'end',title:'End',explanation:'Complete',x:40,y:50}]}};doc.flowOverlay.edges.push(edge('check','a','decision'),edge('yes','decision','b','if'),edge('no','decision','end','if'));const board=s.createBoard(w.id,'Crowded screens',doc);return {s,w,board};}
function geometry(doc){const g=flowGraph(doc),map=new Map(g.nodes.map(n=>[n.id,{left:n.x,top:n.y,width:n.width,height:n.height}]));return doc.flowOverlay.edges.map(e=>({e,points:overlayPath(map.get(e.fromFrameId),map.get(e.toFrameId),{repeat:e.action==='repeat',route:e.route}).points}));}
test('automatic arrangement preserves semantics, captions and child contents in one undoable save',async()=>{const {s,board}=fixture();try{const result=await s.arrangeFlow(board.id,board.revision);assert.equal(result.revision,board.revision+1);assert.equal(s.history(board.id).length,1);assert.equal(result.arrangement.frames,4);assert.notDeepEqual(result.document,board.document);for(const n of result.document.nodes){const original=board.document.nodes.find(o=>o.id===n.id);assert.deepEqual({...n,x:original.x,y:original.y},original);}const a=result.document.nodes.find(n=>n.id==='a'),caption=result.document.nodes.find(n=>n.id==='caption');assert.equal(caption.x,a.x);assert.equal(caption.y-a.y,-40);for(const e of result.document.flowOverlay.edges){const original=board.document.flowOverlay.edges.find(o=>o.id===e.id);assert.deepEqual({...e,route:undefined},{...original,route:undefined});}for(const {points} of geometry(result.document))for(let i=1;i<points.length;i++)assert.ok(Math.abs(points[i].x-points[i-1].x)<.01||Math.abs(points[i].y-points[i-1].y)<.01);const undo=s.travel(board.id,result.revision,'undo');assert.deepEqual(undo.document,board.document);assert.deepEqual(s.travel(board.id,undo.revision,'redo').document,result.document);}finally{s.close();}});
test('arrangement gives each edge its own anchor and keeps linked component contents locked',async()=>{const {s,w,board}=fixture();try{s.saveComponent(board.id,board.revision,'a','Home','component');const c=s.components(w.id)[0],target=s.createBoard(w.id,'Instances',{version:1,nodes:[makeNode('frame',{id:'other',x:1000})]}),insert=s.insertComponent(target.id,1,c.id,{x:0,y:0});let b=insert.board,root=b.document.nodes.find(n=>n.componentId);b=s.mutateFlowOverlay(b.id,b.revision,[{op:'addEdge',edge:edge('one',root.id,'other')},{op:'addEdge',edge:edge('two',root.id,'other')}]);const result=await s.arrangeFlow(b.id,b.revision),next=result.document.nodes.find(n=>n.id===root.id);assert.equal(next.componentId,root.componentId);assert.ok(next.overrides.every(p=>['x','y'].includes(p)));assert.deepEqual(next.instancePlacement,root.instancePlacement);for(const n of result.document.nodes.filter(n=>n.parentId===root.id))assert.deepEqual(n,b.document.nodes.find(o=>o.id===n.id));const anchors=new Set();for(const {e,points} of geometry(result.document)){for(const p of [points[0],points.at(-1)]){const key=p.x+','+p.y;assert.ok(!anchors.has(key));anchors.add(key);}assert.notEqual(e.route.from.offset,0);}assert.throws(()=>s.mutate(b.id,result.revision,[{op:'update',id:next.id,patch:{fill:'#ff0000'}}]),/locked/);}finally{s.close();}});
test('layout is deterministic, rejects empty/unsafe nested geometry, and leaves unrelated artwork untouched',async()=>{const {s,board}=fixture();try{const graph=flowGraph(board.document),a=await computeFlowLayout(graph),b=await computeFlowLayout(graph);assert.deepEqual(a,b);const other=makeNode('frame',{id:'unrelated',x:100,y:50,width:600,height:800});const document={...board.document,nodes:[...board.document.nodes,other]},g=flowGraph(document),applied=applyLayout(document,g,await computeFlowLayout(g)).document;assert.deepEqual(applied.nodes.find(n=>n.id===other.id),other);assert.ok(applied.nodes.find(n=>n.id==='a').x>other.x+other.width);assert.throws(()=>flowGraph({version:1,nodes:[]}),/flow layer/);const nested=structuredClone(board.document);nested.nodes.find(n=>n.id==='b').parentId='a';assert.throws(()=>flowGraph(nested),/contains another/);}finally{s.close();}});
test('concurrent edit during worker calculation is never overwritten; timed-out worker cannot save',async()=>{const {s,board}=fixture();try{const pending=s.arrangeFlow(board.id,board.revision),saved=s.mutate(board.id,board.revision,[{op:'update',id:'child',patch:{text:'New user edit'}}]);await assert.rejects(pending,e=>e.status===409);assert.deepEqual(s.getBoard(board.id).document,saved.document);await assert.rejects(computeFlowLayout(flowGraph(saved.document),{timeout:1}),/exceeded/);assert.equal(s.getBoard(board.id).revision,saved.revision);}finally{s.close();}});
test('flow board references and triggers survive arrangement; compact MCP, HTTP and RPC share the engine',async()=>{const {s,w,board}=fixture(),created=s.createFlowWorkspace('Flow'),ref={workspaceId:w.id,boardId:board.id,frameId:'a'};let flow=s.mutateFlow(created.board.id,1,[{op:'addNode',node:{id:'home',kind:'frame',title:'Home',explanation:'Context',reference:ref,display:'live',width:320,height:500,x:0,y:0}},{op:'addNode',node:{id:'done',kind:'end',title:'Done',explanation:'End',x:20,y:30}},{op:'addEdge',edge:{id:'open',from:'home',to:'done',title:'Complete',explanation:'Done',action:'straight',trigger:{...ref,elementId:'child'}}}]);const server=createServer({store:s});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const receipt=await callTool(s,'freegma_arrange_flow',{boardId:flow.id,expectedRevision:flow.revision});assert.ok(!receipt.document);assert.equal(receipt.arrangement.connections,1);assert.ok(JSON.stringify(receipt).length<1500);flow=s.getBoard(flow.id);assert.deepEqual(flow.document.flow.nodes[0].reference,ref);assert.deepEqual(flow.document.flow.edges[0].trigger,{...ref,elementId:'child'});const response=await fetch('http://127.0.0.1:'+server.address().port+`/api/boards/${flow.id}/arrange`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision:1})});assert.equal(response.status,409);const rpcResult=await rpc(s,{jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'freegma_arrange_flow',arguments:{boardId:flow.id,expectedRevision:flow.revision}}});assert.equal(rpcResult.result.isError,false);assert.equal(rpcResult.result.structuredContent.arrangement.frames,2);}finally{await new Promise(r=>server.close(r));s.close();}});
test('saved label positions render, translate and clear when manually rerouting',()=>{const bounds={left:0,top:0,width:100,height:100},route={from:{side:'right',offset:.5},to:{side:'left',offset:.5},pivots:[{x:200,y:50}],label:{x:180,y:30}},geometry=overlayPath(bounds,{...bounds,left:300},{route});assert.deepEqual(geometry.label,route.label);assert.deepEqual(translatedFlowRoute(geometry,route,20,10).label,{x:200,y:40});assert.equal(draggedFlowRoute(geometry,route,'from',{x:100,y:80},bounds,{...bounds,left:300}).label,undefined);});

test('returns do not reverse the main progression and depart at the bottom',async()=>{const {s,board}=fixture();try{const graph=flowGraph(board.document),plan=await computeFlowLayout(graph),positions=new Map(plan.nodes.map(n=>[n.id,n]));assert.ok(positions.get('a').x<positions.get('decision').x);assert.ok(positions.get('decision').x<positions.get('b').x);const again=plan.edges.find(e=>e.id==='again');assert.equal(again.route.from.side,'bottom');assert.equal(again.route.to.side,'right');assert.equal(again.points[0].x,again.points[1].x);assert.ok(again.points[1].y>again.points[0].y);const applied=applyLayout(board.document,graph,structuredClone(plan)).document;assert.deepEqual((await computeFlowLayout(flowGraph(applied))).nodes,plan.nodes);}finally{s.close();}});


test('short returns reserve a readable label bay without backtracking',async()=>{const s=new FreegmaStore(':memory:',{seed:false});try{const {board}=s.createFlowWorkspace('Short loop');const b=s.mutateFlow(board.id,1,[{op:'addNode',node:{id:'a',kind:'decision',explanation:'',title:'A',x:0,y:0}},{op:'addNode',node:{id:'b',kind:'decision',explanation:'',title:'B',x:10,y:0}},{op:'addNode',node:{id:'c',kind:'decision',explanation:'',title:'C',x:20,y:0}},{op:'addEdge',edge:{id:'ab',from:'a',to:'b',title:'Continue',action:'straight',explanation:''}},{op:'addEdge',edge:{id:'bc',from:'b',to:'c',title:'Complete',action:'straight',explanation:''}},{op:'addEdge',edge:{id:'ca',from:'c',to:'a',title:'Try again with this longer title',action:'repeat',explanation:''}}]);const result=await s.arrangeFlow(b.id,b.revision);assert.equal(result.arrangement.quality.sharedRuns,0);assert.equal(result.arrangement.quality.artworkHits,0);assert.ok(result.document.flow.edges.find(e=>e.id==='ca').route.label);assert.deepEqual(s.travel(b.id,result.revision,'undo').document,b.document);}finally{s.close();}});

test('live reference dimensions follow resized sources and concurrent source edits reject stale layout',async()=>{const {s,w,board}=fixture();try{const flow=s.createFlowWorkspace('Resized reference'),ref={workspaceId:w.id,boardId:board.id,frameId:'a'},b=s.mutateFlow(flow.board.id,1,[{op:'addNode',node:{id:'live',kind:'frame',display:'live',reference:ref,title:'Home',explanation:'',width:20,height:20,x:0,y:0}},{op:'addNode',node:{id:'done',kind:'end',title:'Done',explanation:'',x:100,y:0}},{op:'addEdge',edge:{id:'next',from:'live',to:'done',title:'Complete',explanation:'',action:'straight'}}]);const resized=s.mutate(board.id,board.revision,[{op:'update',id:'a',patch:{width:900,height:1100}}]),result=await s.arrangeFlow(b.id,b.revision),live=result.document.flow.nodes.find(n=>n.id==='live');assert.equal(live.width,900);assert.equal(live.height,1100);assert.deepEqual(s.getBoard(board.id).document,resized.document);const pending=s.arrangeFlow(b.id,result.revision);s.mutate(board.id,resized.revision,[{op:'update',id:'a',patch:{width:1200}}]);await assert.rejects(pending,e=>e.status===409);assert.deepEqual(s.getBoard(b.id).document,result.document);}finally{s.close();}});
