import {decodeFree} from '../server/free-format.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {FreegmaStore} from '../server/store.mjs';
import {createServer} from '../server/http.mjs';
import {callTool,rpc} from '../server/tools.mjs';
import {makeNode} from '../shared/design.mjs';
import {validateFlow,flowLink} from '../shared/flows.mjs';
function setup(){const s=new FreegmaStore(':memory:',{seed:false}),w=s.createWorkspace('Pages'),f=makeNode('frame',{name:'Home'}),button=makeNode('frame',{name:'Buy button',parentId:f.id}),outside=makeNode('text',{name:'Elsewhere'}),b=s.createBoard(w.id,'Shop',{version:1,nodes:[f,button,outside]}),result=s.createFlowWorkspace('Journey');return {s,w,f,button,outside,b,result,ref:{workspaceId:w.id,boardId:b.id,frameId:f.id,name:'Home'}};}
const step=(id,kind,reference)=>({id,kind,title:id,explanation:'Details',x:10,y:20,...(reference?{reference}:{})});
test('flow edits are additive, atomic, undoable, with exact source element references',()=>{const {s,w,b,result,ref,button,outside}=setup();try{
 const before=s.exportFree(w.id).package;let flow=s.mutateFlow(result.board.id,1,[{op:'addNode',node:step('home','frame',ref)},{op:'addNode',node:step('signed_in','if')},{op:'addNode',node:step('retry','repeat')},{op:'addNode',node:step('done','end')},{op:'addEdge',edge:{id:'click',from:'home',to:'signed_in',action:'straight',title:'Buy',explanation:'Click buy',trigger:{...ref,elementId:button.id}}}]);
 assert.deepEqual(s.exportFree(w.id).package,before);assert.equal(s.workspace(result.workspace.id).type,'flows');assert.equal(s.flowSources(b.id).frames.length,2);assert.equal(s.flowSources(b.id,ref.frameId).elements.length,2);
 assert.throws(()=>s.mutateFlow(flow.id,1,[{op:'removeNode',id:'home'}]),e=>e.status===409);
 assert.throws(()=>s.mutateFlow(flow.id,flow.revision,[{op:'updateNode',id:'home',patch:{x:77}},{op:'updateEdge',id:'click',patch:{trigger:{...ref,elementId:outside.id}}}]),/outside/);assert.deepEqual(s.getBoard(flow.id),flow);
 assert.throws(()=>s.mutateFlow(flow.id,flow.revision,[{op:'addEdge',edge:{id:'wrong',from:'done',to:'home',action:'straight',title:'',explanation:''}}]),/End states/);
 flow=s.mutateFlow(flow.id,flow.revision,[{op:'addEdge',edge:{id:'loop',from:'retry',to:'retry',action:'repeat',title:'Until ready',explanation:''}},{op:'addEdge',edge:{id:'yes',from:'signed_in',to:'done',action:'if',title:'Yes',explanation:'Session present'}}]);
 flow=s.mutateFlow(flow.id,flow.revision,[{op:'removeNode',id:'signed_in'}]);assert.equal(flow.document.flow.edges.length,1);flow=s.travel(flow.id,flow.revision,'undo');assert.equal(flow.document.flow.edges.length,3);flow=s.travel(flow.id,flow.revision,'redo');assert.equal(flow.document.flow.edges.length,1);
 assert.throws(()=>s.export(flow.id),/referenced design board/);assert.doesNotThrow(()=>s.export(b.id));
 const preview=s.flowPreview(b.id,ref.frameId);assert.equal(preview.document.nodes.length,2);assert.equal(preview.document.nodes[0].parentId,null);assert.equal(preview.paletteRevision,s.colors(w.id).revision);
 assert.doesNotThrow(()=>s.mutate(b.id,b.revision,[{op:'add',node:makeNode('frame')}])); // Source remains editable independently.
 }finally{s.close();}});
test('missing source frames are reported, without deleting the logical diagram',()=>{const {s,b,f,result,ref}=setup();try{const flow=s.mutateFlow(result.board.id,1,[{op:'addNode',node:step('home','frame',ref)}]);s.mutate(b.id,b.revision,[{op:'remove',id:f.id}]);assert.equal(s.flowReference(ref).available,false);const moved=s.mutateFlow(flow.id,flow.revision,[{op:'updateNode',id:'home',patch:{x:333}}]);assert.equal(moved.document.flow.nodes[0].x,333);assert.equal(s.flowReference({...ref,workspaceId:'wrong'}).available,false);}finally{s.close();}});
test('.free flow packages preserve diagram and history; cross-type imports are rejected',()=>{const {s,w,result,ref}=setup();try{let b=s.mutateFlow(result.board.id,1,[{op:'addNode',node:step('home','frame',ref)}]);b=s.mutateFlow(b.id,b.revision,[{op:'updateNode',id:'home',patch:{explanation:'Click a button next'}}]);const pkg=s.exportFree(result.workspace.id).package,copy=s.importFree(pkg);assert.equal(copy.workspace.type,'flows');assert.deepEqual(copy.boards[0].document,b.document);assert.equal(s.history(copy.boards[0].id).length,2);assert.throws(()=>s.importFree(s.exportFree(b.id,'board').package,w.id),/Import Flows/);assert.throws(()=>s.createBoard(w.id,'Bad',b.document),/types must match/);assert.throws(()=>s.replace(b.id,b.revision,{version:1,nodes:[]}),/types must match/);assert.equal(s.createBoard(result.workspace.id,'Another').document.flow.nodes.length,0);}finally{s.close();}});
test('flow files survive server restart; SQLite still contains only file references',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'flows-')),db=path.join(dir,'index.sqlite');let s=new FreegmaStore(db,{seed:false});try{const {workspace,board}=s.createFlowWorkspace('Persisted');const edited=s.mutateFlow(board.id,1,[{op:'addNode',node:step('done','end')}]);s.close();s=new FreegmaStore(db,{seed:false});assert.equal(s.workspaces().find(w=>w.id===workspace.id).type,'flows');assert.deepEqual(s.getBoard(board.id).document,edited.document);assert.equal(decodeFree(fs.readFileSync(s.getBoard(board.id).filePath)).value.document.flow.nodes[0].kind,'end');assert.deepEqual(s.db.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all().map(r=>r.name),['file_refs','settings']);}finally{s.close();fs.rmSync(dir,{recursive:true,force:true});}});
test('MCP discovers and uses independent flow tools',()=>{const {s,result}=setup();try{const listed=rpc(s,{jsonrpc:'2.0',id:1,method:'tools/list'}).result.tools;for(const name of ['freegma_create_flow_workspace','freegma_flow_sources','freegma_apply_flow'])assert.ok(listed.some(t=>t.name===name));const b=callTool(s,'freegma_apply_flow',{boardId:result.board.id,expectedRevision:1,operations:[{op:'addNode',node:step('done','end')}]});assert.equal(b.document.flow.nodes.length,1);assert.match(flowLink({workspaceId:'workspace_a',boardId:'board_b',frameId:'frame_c'}),/\?node=frame_c$/);}finally{s.close();}});
test('flow APIs return bounded source metadata and enforce revisions',async()=>{const {s,b,f}=setup(),server=createServer({store:s});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{const response=await fetch(base+'/api/flow-workspaces',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'API journey'})});assert.equal(response.status,201);const created=await response.json(),frames=await(await fetch(base+`/api/boards/${b.id}/flow-sources`)).json();assert.ok(frames.frames.some(n=>n.id===f.id));assert.equal(frames.document,undefined);const saved=await fetch(base+`/api/boards/${created.board.id}/flow`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision:1,operations:[{op:'addNode',node:step('done','end')}]})});assert.equal(saved.status,200);const stale=await fetch(base+`/api/boards/${created.board.id}/flow`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision:1,operations:[{op:'removeNode',id:'done'}]})});assert.equal(stale.status,409);}finally{await new Promise(r=>server.close(r));s.close();}});
test('flow validation rejects unsafe IDs, malformed references, cycles without repeat and excessive payloads',()=>{const node=step('a','repeat');for(const flow of [{version:1,nodes:[node],edges:[{id:'bad',from:'a',to:'a',action:'straight',title:'',explanation:''}]},{version:1,nodes:[step('../unsafe','end')],edges:[]},{version:1,nodes:[step('a','frame',{workspaceId:'x',boardId:'y'})],edges:[]},{version:1,nodes:Array(1001).fill(node),edges:[]}])assert.throws(()=>validateFlow(flow));});
