import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {FreegmaStore} from '../server/store.mjs';
import {createServer} from '../server/http.mjs';
import {callTool,rpc} from '../server/tools.mjs';
import {makeNode,validateDocument} from '../shared/design.mjs';
import {applyOverlayOperations,overlayPath} from '../shared/flow-overlay.mjs';
function setup(store=new FreegmaStore(':memory:',{seed:false})){
 const w=store.createWorkspace('Pages'),home=makeNode('frame',{name:'Home',x:10,y:20,width:400,height:300}),next=makeNode('frame',{name:'Next',x:610,y:20,width:400,height:300}),button=makeNode('frame',{name:'Continue',parentId:home.id,x:20,y:180,width:120,height:40}),label=makeNode('text',{name:'Button label',parentId:button.id,text:'Continue'}),outside=makeNode('text',{parentId:next.id});
 const b=store.createBoard(w.id,'Pages',{version:1,nodes:[home,next,button,label,outside]}),edge={id:'continue',fromFrameId:home.id,toFrameId:next.id,triggerId:button.id,action:'straight',title:'Continue',explanation:'Click Continue to open the next screen.'};return {s:store,w,b,home,next,button,label,outside,edge};
}
test('overlay references actual native frames without changing design properties, CSS or React',()=>{const {s,b,edge}=setup();try{
 const code=s.export(b.id),updated=s.mutateFlowOverlay(b.id,1,[{op:'addEdge',edge}]);assert.deepEqual(updated.document.nodes,b.document.nodes);const exported=s.export(b.id);for(const key of ['code','jsxCode','css','assets'])assert.deepEqual(exported[key],code[key]);assert.equal(s.workspace(b.workspaceId).type,undefined);assert.equal(updated.document.flow,undefined);
 assert.equal(updated.document.flowOverlay.edges[0].triggerId,edge.triggerId);assert.deepEqual(s.travel(b.id,updated.revision,'undo').document,b.document);const undone=s.getBoard(b.id);assert.deepEqual(s.travel(b.id,undone.revision,'redo').document,updated.document);
}finally{s.close();}});
test('overlay validates exact source trigger ancestry and atomic revisions',()=>{const {s,b,edge,outside,label}=setup();try{
 let updated=s.mutateFlowOverlay(b.id,1,[{op:'addEdge',edge:{...edge,triggerId:label.id}}]);assert.throws(()=>s.mutateFlowOverlay(b.id,1,[{op:'removeEdge',id:edge.id}]),e=>e.status===409);
 assert.throws(()=>s.mutateFlowOverlay(b.id,updated.revision,[{op:'updateEdge',id:edge.id,patch:{title:'Should roll back'}},{op:'updateEdge',id:edge.id,patch:{triggerId:outside.id}}]),/source frame/);assert.deepEqual(s.getBoard(b.id),updated);
 updated=s.mutateFlowOverlay(b.id,updated.revision,[{op:'updateEdge',id:edge.id,patch:{triggerId:null,title:'When ready',explanation:'A state transition',action:'if'}}]);assert.equal(updated.document.flowOverlay.edges[0].triggerId,null);
}finally{s.close();}});
test('removing a source frame, target frame or trigger prunes arrows; undo restores artwork and arrows together',()=>{for(const kind of ['home','next','button']){const ctx=setup(),{s,b,edge}=ctx;try{const updated=s.mutateFlowOverlay(b.id,1,[{op:'addEdge',edge}]),removed=s.mutate(b.id,updated.revision,[{op:'remove',id:ctx[kind].id}]);assert.equal(removed.document.flowOverlay.edges.length,0);assert.deepEqual(s.travel(b.id,removed.revision,'undo').document,updated.document);}finally{s.close();}}});
test('native moves keep IDs and flow arrows while reparenting an exact trigger clears its transition',()=>{const {s,b,edge,home,next,button}=setup();try{let updated=s.mutateFlowOverlay(b.id,1,[{op:'addEdge',edge}]);updated=s.mutate(b.id,updated.revision,[{op:'update',id:home.id,patch:{x:333,y:90}}]);assert.deepEqual(updated.document.flowOverlay.edges,[edge]);updated=s.mutate(b.id,updated.revision,[{op:'update',id:button.id,patch:{parentId:next.id}}]);assert.equal(updated.document.flowOverlay.edges.length,0);}finally{s.close();}});
test('repeat self loops are valid, malformed payloads and non-frame endpoints are rejected',()=>{const {s,b,edge,label}=setup();try{assert.doesNotThrow(()=>applyOverlayOperations(b.document,[{op:'addEdge',edge:{...edge,toFrameId:edge.fromFrameId,action:'repeat'}}]));
 for(const patch of [{toFrameId:edge.fromFrameId},{toFrameId:label.id},{id:'../bad'},{title:''},{title:'x'.repeat(161)},{explanation:'x'.repeat(10001)},{action:'unknown'},{unexpected:'property'}])assert.throws(()=>applyOverlayOperations(b.document,[{op:'addEdge',edge:{...edge,...patch}}]));
 assert.throws(()=>validateDocument({...b.document,flowOverlay:{version:1,edges:[edge,edge]}}));assert.throws(()=>applyOverlayOperations({version:1,nodes:[],flow:{version:1,nodes:[],edges:[]}},[{op:'addEdge',edge}]),/native design/);
}finally{s.close();}});
test('remove, edit and undo each save one flow change; portable .free retains the overlay and its history',()=>{const {s,w,b,edge}=setup();try{let updated=s.mutateFlowOverlay(b.id,1,[{op:'addEdge',edge}]);updated=s.mutateFlowOverlay(b.id,updated.revision,[{op:'updateEdge',id:edge.id,patch:{title:'Open next',explanation:'New details'}}]);updated=s.mutateFlowOverlay(b.id,updated.revision,[{op:'removeEdge',id:edge.id}]);const restored=s.travel(b.id,updated.revision,'undo');assert.equal(restored.document.flowOverlay.edges[0].title,'Open next');assert.equal(s.history(b.id).length,3);
 const copy=s.importFree(s.exportFree(w.id).package);assert.equal(copy.workspace.type,undefined);assert.deepEqual(copy.boards[0].document,restored.document);assert.equal(s.history(copy.boards[0].id).length,3);
}finally{s.close();}});
test('shared component sync preserves flows and cleans references only when the triggering layer is removed',()=>{const {s,w,b,edge,home,button,label}=setup();try{
 const published=s.saveComponent(b.id,1,button.id,'Continue button','component'),library=s.components(w.id),component=library.find(c=>c.name==='Continue button');
 let board=s.getBoard(b.id);board=s.mutateFlowOverlay(b.id,board.revision,[{op:'addEdge',edge:{...edge,triggerId:label.id}}]);
 const target=s.createBoard(w.id,'Instance',{version:1,nodes:[makeNode('frame',{id:'another',name:'Other screen'})]});let instance=s.insertComponent(target.id,1,component.id,{x:500,y:0}).board;const root=instance.document.nodes.find(n=>n.componentId===component.id),child=instance.document.nodes.find(n=>n.sourceId===label.id);
 instance=s.mutateFlowOverlay(instance.id,instance.revision,[{op:'addEdge',edge:{...edge,fromFrameId:root.id,toFrameId:'another',triggerId:child.id}}]);board=s.mutate(board.id,board.revision,[{op:'update',id:label.id,patch:{text:'Changed master'}}]);assert.equal(s.getBoard(instance.id).document.flowOverlay.edges.length,1);
 s.mutate(board.id,board.revision,[{op:'remove',id:label.id}]);assert.equal(s.getBoard(instance.id).document.flowOverlay.edges.length,0);
}finally{s.close();}});
test('overlay survives restart in .free files and SQLite remains a file-reference index',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'overlay-')),db=path.join(dir,'index.sqlite');let s=new FreegmaStore(db,{seed:false});try{const {b,edge}=setup(s),updated=s.mutateFlowOverlay(b.id,1,[{op:'addEdge',edge}]);s.close();s=new FreegmaStore(db,{seed:false});assert.deepEqual(s.getBoard(b.id).document,updated.document);assert.deepEqual(s.db.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all().map(r=>r.name),['file_refs','settings']);}finally{s.close();fs.rmSync(dir,{recursive:true,force:true});}});
test('MCP and HTTP expose overlay operations with revision protection',async()=>{const {s,b,edge}=setup(),server=createServer({store:s});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{
 assert.ok(rpc(s,{jsonrpc:'2.0',id:1,method:'tools/list'}).result.tools.some(t=>t.name==='freegma_apply_flow_overlay'));const updated=callTool(s,'freegma_apply_flow_overlay',{boardId:b.id,expectedRevision:1,operations:[{op:'addEdge',edge}]});const base='http://127.0.0.1:'+server.address().port,save=(revision)=>fetch(base+`/api/boards/${b.id}/flow-overlay`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision:revision,operations:[{op:'removeEdge',id:edge.id}]})});assert.equal((await save(1)).status,409);assert.equal((await save(updated.revision)).status,200);
}finally{await new Promise(r=>server.close(r));s.close();}});
test('arrow geometry follows native frame movement, supports vertical links, parallel lanes and repeat loops',()=>{const a={left:10,top:20,width:400,height:300},b={left:610,top:20,width:400,height:300};const p=overlayPath(a,b);assert.equal(p.points[0].x,410);assert.equal(p.points[3].x,610);assert.equal(p.label.x,510);const moved=overlayPath({...a,left:50},b);assert.equal(moved.points[0].x,450);assert.notDeepEqual(overlayPath(a,b,{lane:1}).label,p.label);const loop=overlayPath(a,a,{loop:true});assert.equal(loop.points[0].x,410);assert.equal(loop.points[3].y,320);const repeat=overlayPath(b,a,{repeat:true});assert.equal(repeat.points[0].y,320);assert.equal(repeat.points[3].y,320);assert.ok(repeat.label.y>320);const vertical=overlayPath(a,{...b,left:10,top:620});assert.equal(vertical.points[0].y,320);assert.equal(vertical.points[3].y,620);});
test('full-size overlay references connect designs from another workspace without changing their source',()=>{const {s,b,edge,home}=setup();try{
 const source=setup(s),reference={workspaceId:source.w.id,boardId:source.b.id,frameId:source.home.id,name:'Referenced home'},frame={id:'linked_home',reference,x:1300,y:100,width:400,height:300},original=s.getBoard(source.b.id);
 let board=s.mutateFlowOverlay(b.id,b.revision,[{op:'addFrame',frame},{op:'addEdge',edge:{...edge,fromFrameId:frame.id,toFrameId:home.id,triggerId:source.button.id}}]);assert.deepEqual(s.getBoard(source.b.id),original);assert.deepEqual(board.document.nodes,b.document.nodes);
 assert.throws(()=>s.mutateFlowOverlay(b.id,board.revision,[{op:'updateEdge',id:edge.id,patch:{triggerId:source.outside.id}}]),/outside/);assert.throws(()=>s.mutateFlowOverlay(b.id,board.revision,[{op:'updateFrame',id:frame.id,patch:{reference:{...reference,frameId:source.next.id}}}]),/outside/);
 board=s.mutateFlowOverlay(b.id,board.revision,[{op:'updateFrame',id:frame.id,patch:{x:1500,y:300}}]);assert.equal(board.document.flowOverlay.frames[0].x,1500);
 board=s.mutateFlowOverlay(b.id,board.revision,[{op:'removeFrame',id:frame.id}]);assert.equal(board.document.flowOverlay.frames.length,0);assert.equal(board.document.flowOverlay.edges.length,0);board=s.travel(b.id,board.revision,'undo');assert.equal(board.document.flowOverlay.edges.length,1);assert.deepEqual(s.getBoard(source.b.id),original);
}finally{s.close();}});
test('overlay reference additions are checked atomically and missing original frames remain recoverable',()=>{const {s,b,edge,home,button}=setup();try{
 const reference={workspaceId:b.workspaceId,boardId:b.id,frameId:home.id},frame={id:'ref',reference,x:0,y:0,width:400,height:300};assert.throws(()=>s.mutateFlowOverlay(b.id,1,[{op:'addFrame',frame:{...frame,reference:{...reference,frameId:'missing'}}}]),/missing/);assert.equal(s.getBoard(b.id).revision,1);
 let board=s.mutateFlowOverlay(b.id,1,[{op:'addFrame',frame},{op:'addEdge',edge:{...edge,fromFrameId:frame.id,triggerId:button.id}}]);board=s.mutate(b.id,board.revision,[{op:'remove',id:home.id}]);assert.equal(board.document.flowOverlay.frames.length,1);assert.equal(board.document.flowOverlay.edges.length,1);assert.equal(s.flowReference(reference).available,false);
 board=s.mutateFlowOverlay(b.id,board.revision,[{op:'updateEdge',id:edge.id,patch:{title:'Missing source can be repaired'}}]);assert.equal(board.document.flowOverlay.edges[0].title,'Missing source can be repaired');
}finally{s.close();}});
test('portable project remaps overlay references to its own imported board identities',()=>{const {s,w,b,edge,home}=setup();try{
 const source=s.createBoard(w.id,'Source',{version:1,nodes:[makeNode('frame',{id:'external_frame',name:'Source'}),makeNode('text',{id:'external_button',parentId:'external_frame'})]});const frame={id:'ref',reference:{workspaceId:w.id,boardId:source.id,frameId:'external_frame'},x:1000,y:0,width:240,height:160};s.mutateFlowOverlay(b.id,1,[{op:'addFrame',frame},{op:'addEdge',edge:{...edge,fromFrameId:'ref',triggerId:'external_button'}}]);
 const imported=s.importFree(s.exportFree(w.id).package),target=imported.boards.find(board=>board.name==='Pages'),ref=target.document.flowOverlay.frames[0].reference;assert.equal(ref.workspaceId,imported.workspace.id);assert.equal(ref.boardId,imported.boards.find(board=>board.name==='Source').id);assert.notEqual(ref.boardId,source.id);assert.equal(s.flowReference({...ref,elementId:'external_button'}).available,true);
}finally{s.close();}});
test('portable interactive example has native frames and a working cross-board overlay without task identities',()=>{const pkg=JSON.parse(fs.readFileSync(new URL('../examples/Flow-Overlay-Example.free',import.meta.url),'utf8')),s=new FreegmaStore(':memory:',{seed:false});try{
 const imported=s.importFree(pkg),board=imported.boards.find(b=>b.document.flowOverlay);assert.equal(imported.boards.length,2);assert.equal(board.document.flowOverlay.edges.length,2);assert.equal(board.document.flowOverlay.frames.length,1);assert.equal(board.document.nodes.filter(n=>!n.parentId).length,2);const ref=board.document.flowOverlay.frames[0].reference,edge=board.document.flowOverlay.edges.find(e=>e.fromFrameId===board.document.flowOverlay.frames[0].id);assert.equal(s.flowReference({...ref,elementId:edge.triggerId}).available,true);assert.ok(imported.boards.every(b=>!b.taskRef));assert.doesNotThrow(()=>s.export(board.id));
}finally{s.close();}});
test('feature example contains four editable mockups for the canvas overlay, hover, editor and references',()=>{const pkg=JSON.parse(fs.readFileSync(new URL('../examples/Flow-Overlay-Feature.free',import.meta.url),'utf8')),s=new FreegmaStore(':memory:',{seed:false});try{const {boards}=s.importFree(pkg),doc=boards[0].document;assert.equal(doc.nodes.filter(n=>!n.parentId).length,4);assert.ok(doc.nodes.some(n=>n.name==='Transition hover popover'));assert.ok(doc.nodes.some(n=>n.name==='Reference caption'));assert.equal(boards[0].taskRef,'');assert.doesNotThrow(()=>s.export(boards[0].id));}finally{s.close();}});
test('referenced schematic frames render the same live colors in their read-only preview',()=>{const {s,w,b,home}=setup();try{const inserted=s.insertColorSchematic(b.id,b.revision,{x:0,y:0});const frame=inserted.board.document.nodes.find(n=>n.colorSchematic),preview=s.flowPreview(b.id,frame.id);assert.ok(preview.document.nodes.length>1);assert.ok(preview.document.nodes.some(n=>n.type==='text'&&n.text.includes('Background')));assert.equal(preview.document.nodes[0].colorSchematic,undefined);}finally{s.close();}});
