import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {gunzipSync} from 'node:zlib';
import {createServer} from '../server/http.mjs';import {acceptsGzip} from '../server/text-response.mjs';import {FreegmaStore} from '../server/store.mjs';import {makeNode} from '../shared/design.mjs';
function request(server,route,{method='GET',headers={},body}={}){return new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port:server.address().port,path:route,method,headers,timeout:5000},res=>{const chunks=[];res.on('data',v=>chunks.push(v));res.on('error',reject);res.on('end',()=>{const wire=Buffer.concat(chunks);resolve({status:res.statusCode,headers:res.headers,wire,body:wire.length&&res.headers['content-encoding']==='gzip'?gunzipSync(wire):wire});});});req.on('timeout',()=>req.destroy(Error('Local HTTP timeout')));req.on('error',reject);req.end(body);});}
test('compression respects explicit gzip exclusion, wildcard fallback and quality values',()=>{
 for(const h of ['gzip','br, gzip;q=0.5','GZIP; q=1','*;q=0.5'])assert.equal(acceptsGzip(h),true,h);
 for(const h of [undefined,'','identity','br','gzip;q=0','gzip;q=0,*;q=1','gzip;q=bad','gzip;q=2','*;q=0'])assert.equal(acceptsGzip(h),false,String(h));
});
test('large live board reads and saves compress without caching or changing revisions and errors',async()=>{
 const store=new FreegmaStore(':memory:',{seed:false}),w=store.createWorkspace('Transfer test'),b=store.createBoard(w.id,'Board',{nodes:Array.from({length:30},(_,i)=>makeNode('text',{id:'text_'+i,text:'Editable text '.repeat(20)}))}),server=createServer({store,access:()=>({})});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 try{const route='/api/boards/'+b.id,plain=await request(server,route),packed=await request(server,route,{headers:{'Accept-Encoding':'gzip'}});assert.equal(packed.status,200);assert.equal(packed.headers['content-encoding'],'gzip');assert.deepEqual(packed.body,plain.body);assert.equal(packed.wire.length,Number(packed.headers['content-length']));assert.ok(packed.wire.length<plain.wire.length/2);assert.equal(packed.headers['cache-control'],'no-store');assert.equal(packed.headers.vary,'Accept-Encoding');assert.equal(packed.headers.etag,undefined);
 const excluded=await request(server,route,{headers:{'Accept-Encoding':'gzip;q=0,*;q=1'}});assert.deepEqual(excluded.wire,plain.wire);assert.equal(excluded.headers['content-encoding'],undefined);
 const update={expectedRevision:b.revision,operations:[{op:'update',id:'text_0',patch:{text:'Changed'}}]},options={method:'POST',headers:{'Content-Type':'application/json','Accept-Encoding':'gzip'},body:JSON.stringify(update)},saved=await request(server,route+'/operations',options);assert.equal(saved.status,200);assert.equal(JSON.parse(saved.body).revision,b.revision+1);assert.equal(JSON.parse(saved.body).document.nodes[0].text,'Changed');assert.equal(saved.headers['cache-control'],'no-store');assert.equal(saved.headers['content-encoding'],'gzip');
 const stale=await request(server,route+'/operations',options);assert.equal(stale.status,409);assert.match(JSON.parse(stale.body).error,/changed elsewhere/);const current=await request(server,route,{headers:{'Accept-Encoding':'gzip','If-None-Match':'*'}});assert.equal(current.status,200);assert.equal(JSON.parse(current.body).revision,b.revision+1);
 const text='export const Example = "'+ 'design '.repeat(300)+'";',download=await request(server,'/api/source-downloads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:'Example.jsx',content:text})});const downloaded=await request(server,JSON.parse(download.body).url,{headers:{'Accept-Encoding':'gzip'}});assert.equal(downloaded.body.toString(),text);assert.equal(downloaded.headers['cache-control'],'no-store');assert.match(downloaded.headers['content-disposition'],/Example\.jsx/);
 }finally{await new Promise(r=>server.close(r));store.close();}
});
test('editor ETags avoid repeat bodies, distinguish encodings and invalidate replaced build files',async()=>{
 const folder=fs.mkdtempSync(path.join(os.tmpdir(),'freegma-transfer-')),store=new FreegmaStore(':memory:',{seed:false});const original='const version=1;'+ '// editor\n'.repeat(300),updated=original.replace('version=1','version=2');fs.writeFileSync(path.join(folder,'app.js'),original);fs.writeFileSync(path.join(folder,'index.html'),'<html>Design studio</html>');const server=createServer({store,build:folder,access:()=>({})});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 try{const headers={'Accept-Encoding':'gzip'},first=await request(server,'/app.js',{headers}),etag=first.headers.etag;assert.equal(first.body.toString(),original);assert.equal(first.headers['content-encoding'],'gzip');assert.equal(first.headers['cache-control'],'no-cache');assert.equal(first.headers.vary,'Accept-Encoding');
 const cached=await request(server,'/app.js',{headers:{...headers,'If-None-Match':'W/'+etag}});assert.equal(cached.status,304);assert.equal(cached.wire.length,0);assert.equal(cached.headers.etag,etag);const head=await request(server,'/app.js',{method:'HEAD',headers});assert.equal(head.status,200);assert.equal(head.wire.length,0);assert.equal(Number(head.headers['content-length']),first.wire.length);
 const identity=await request(server,'/app.js',{headers:{'If-None-Match':etag}});assert.equal(identity.status,200);assert.equal(identity.body.toString(),original);assert.notEqual(identity.headers.etag,etag);assert.equal(identity.headers['content-encoding'],undefined);
 fs.writeFileSync(path.join(folder,'app.js'),updated);fs.utimesSync(path.join(folder,'app.js'),new Date(),new Date(Date.now()+2000));const changed=await request(server,'/app.js',{headers:{...headers,'If-None-Match':etag}});assert.equal(changed.status,200);assert.equal(changed.body.toString(),updated);assert.notEqual(changed.headers.etag,etag);const fresh=await request(server,'/app.js',{headers:{...headers,'If-None-Match':changed.headers.etag}});assert.equal(fresh.status,304);
 const page=await request(server,'/w/demo/b/demo');assert.equal(page.body.toString(),'<html>Design studio</html>');const revisit=await request(server,'/w/demo/b/demo',{headers:{'If-None-Match':page.headers.etag}});assert.equal(revisit.status,304);assert.equal(revisit.wire.length,0);
 }finally{await new Promise(r=>server.close(r));store.close();fs.rmSync(folder,{recursive:true,force:true});}
});
