import {applyOverlayOperations} from '../shared/flow-overlay.mjs';
import {emptyFlow,applyFlowOperations,validateReference} from '../shared/flows.mjs';
import {descendants,subtree,makeNode} from '../shared/design.mjs';
import {resolveOwnedDocument,materializeOwnedSchematics} from '../shared/colors.mjs';
const fail=(m,status=400)=>{throw Object.assign(new Error(m),{status});};
// Preview needs the same source guards, without constructing picker metadata.
const sourceFrame=(board,frameId)=>{if(board.document.flow)fail('Pick a design board, not a flow.');if(!frameId)return null;const frame=board.document.nodes.find(n=>n.id===frameId&&n.type==='frame');if(!frame)fail('Referenced frame is missing.',404);return frame;};
export const flowStoreMethods={
 mutateFlowOverlay(id,revision,operations,label='Edit flow layer'){return this.transaction(()=>{const b=this.getBoard(id);this.expect(b,revision);const doc=applyOverlayOperations(b.document,operations),refs=new Map((doc.flowOverlay.frames||[]).map(f=>[f.id,f]));for(const op of operations){if(op.op==='addFrame')this.checkFlowReference(op.frame.reference);if(op.op==='updateFrame'&&op.patch.reference)this.checkFlowReference(op.patch.reference);if(op.op==='addEdge'||op.op==='updateEdge'){const edge=doc.flowOverlay.edges.find(e=>e.id===(op.edge?.id||op.id)),source=refs.get(edge?.fromFrameId);if(source&&(op.op==='addEdge'||Object.hasOwn(op.patch,'fromFrameId')||Object.hasOwn(op.patch,'triggerId')))this.checkFlowReference({...source.reference,...(edge.triggerId?{elementId:edge.triggerId}:{})});}}for(const op of operations.filter(op=>op.op==='updateFrame'&&op.patch.reference)){const source=refs.get(op.id);for(const edge of doc.flowOverlay.edges.filter(e=>e.fromFrameId===op.id))this.checkFlowReference({...source.reference,...(edge.triggerId?{elementId:edge.triggerId}:{})});}return this.writeBoard(b,doc,label);});},
 createFlowWorkspace(name,parentId=null){return this.transaction(()=>{const workspace=this.createWorkspace(name,parentId);const manifest=this.manifest(workspace.id);manifest.type='flows';this.stageManifest(manifest);return {workspace:this.workspace(workspace.id),board:this.createBoard(workspace.id,'Untitled flow',emptyFlow())};});},
 flowSources(boardId,frameId=null){const b=this.readBoard(boardId,false),f=sourceFrame(b,frameId);if(!frameId)return {boardId,workspaceId:b.workspaceId,frames:b.document.nodes.filter(n=>n.type==='frame').map(n=>({id:n.id,name:n.name,width:n.width,height:n.height,parentId:n.parentId}))};return {boardId,workspaceId:b.workspaceId,frame:{id:f.id,name:f.name,width:f.width,height:f.height},elements:descendants(b.document.nodes,frameId).map(n=>({id:n.id,name:n.name,type:n.type,text:n.type==='text'?n.text.slice(0,120):undefined}))};},
 checkFlowReference(ref){validateReference(ref);const b=this.readBoard(ref.boardId,false);if(b.workspaceId!==ref.workspaceId||b.document.flow)fail('Reference must point to its original design workspace.');const source=this.flowSources(ref.boardId,ref.frameId);if(ref.elementId&&!source.elements.some(n=>n.id===ref.elementId))fail('Trigger element is outside the source frame.');return source;},
 flowReference(ref){try{const source=this.checkFlowReference(ref);return {available:true,workspaceName:this.manifest(ref.workspaceId,false).name,boardName:this.readBoard(ref.boardId,false).name,frameName:source.frame.name,elementName:source.elements.find(n=>n.id===ref.elementId)?.name};}catch(e){return {available:false,message:e.message};}},
 flowPreview(boardId,frameId){const b=this.readBoard(boardId,false);sourceFrame(b,frameId);const palette=this.colors(b.workspaceId),frame=subtree(b.document,frameId);return {revision:b.revision,paletteRevision:palette.revision,themeId:palette.themeId,document:materializeOwnedSchematics(resolveOwnedDocument(frame,palette),palette,makeNode)};},
 mutateFlow(id,revision,operations,label='Edit flow'){return this.transaction(()=>{const b=this.getBoard(id);this.expect(b,revision);if(this.manifest(b.workspaceId,false).type!=='flows')fail('Open a Flows workspace first.');const doc=applyFlowOperations(b.document,operations);for(const op of operations){if(op.op==='addNode'&&op.node.reference)this.checkFlowReference(op.node.reference);if(op.op==='updateNode'&&op.patch.reference)this.checkFlowReference(op.patch.reference);if(op.op==='addEdge'&&op.edge.trigger)this.checkFlowReference(op.edge.trigger);if(op.op==='updateEdge'&&op.patch.trigger)this.checkFlowReference(op.patch.trigger);}return this.writeBoard(b,doc,label);});}
};
