import {emptyFlow,applyFlowOperations,validateReference} from '../shared/flows.mjs';
import {descendants,subtree} from '../shared/design.mjs';
import {resolveDocument} from '../shared/colors.mjs';
const fail=(m,status=400)=>{throw Object.assign(new Error(m),{status});};
export const flowStoreMethods={
 createFlowWorkspace(name,parentId=null){return this.transaction(()=>{const workspace=this.createWorkspace(name,parentId);const manifest=this.manifest(workspace.id);manifest.type='flows';this.stageManifest(manifest);return {workspace:this.workspace(workspace.id),board:this.createBoard(workspace.id,'Untitled flow',emptyFlow())};});},
 flowSources(boardId,frameId=null){const b=this.readBoard(boardId,false);if(b.document.flow)fail('Pick a design board, not a flow.');if(!frameId)return {boardId,workspaceId:b.workspaceId,frames:b.document.nodes.filter(n=>n.type==='frame').map(n=>({id:n.id,name:n.name,width:n.width,height:n.height,parentId:n.parentId}))};const f=b.document.nodes.find(n=>n.id===frameId&&n.type==='frame');if(!f)fail('Referenced frame is missing.',404);return {boardId,workspaceId:b.workspaceId,frame:{id:f.id,name:f.name},elements:descendants(b.document.nodes,frameId).map(n=>({id:n.id,name:n.name,type:n.type,text:n.type==='text'?n.text.slice(0,120):undefined}))};},
 checkFlowReference(ref){validateReference(ref);const b=this.readBoard(ref.boardId,false);if(b.workspaceId!==ref.workspaceId||b.document.flow)fail('Reference must point to its original design workspace.');const source=this.flowSources(ref.boardId,ref.frameId);if(ref.elementId&&!source.elements.some(n=>n.id===ref.elementId))fail('Trigger element is outside the source frame.');return source;},
 flowReference(ref){try{const source=this.checkFlowReference(ref);return {available:true,workspaceName:this.manifest(ref.workspaceId,false).name,boardName:this.readBoard(ref.boardId,false).name,frameName:source.frame.name,elementName:source.elements.find(n=>n.id===ref.elementId)?.name};}catch(e){return {available:false,message:e.message};}},
 flowPreview(boardId,frameId){const b=this.readBoard(boardId,false);this.flowSources(boardId,frameId);const palette=this.colors(b.workspaceId);return {revision:b.revision,paletteRevision:palette.revision,themeId:palette.themeId,document:subtree(resolveDocument(b.document,palette),frameId)};},
 mutateFlow(id,revision,operations,label='Edit flow'){return this.transaction(()=>{const b=this.getBoard(id);this.expect(b,revision);if(this.manifest(b.workspaceId,false).type!=='flows')fail('Open a Flows workspace first.');const doc=applyFlowOperations(b.document,operations);for(const op of operations){if(op.op==='addNode'&&op.node.reference)this.checkFlowReference(op.node.reference);if(op.op==='updateNode'&&op.patch.reference)this.checkFlowReference(op.patch.reference);if(op.op==='addEdge'&&op.edge.trigger)this.checkFlowReference(op.edge.trigger);if(op.op==='updateEdge'&&op.patch.trigger)this.checkFlowReference(op.patch.trigger);}return this.writeBoard(b,doc,label);});}
};
